### ISSUE TITLE
Failed: OrientDBFlow should kafka-example - store documents and pass Responses with passThrough

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1029]
```
[info] OrientDBFlow
title: Book 1
title: Book 2
title: Book 3
[info] - should kafka-example - store documents and pass Responses with passThrough *** FAILED *** (106 milliseconds)
[info]   List(0, 1, 2) did not equal List() (OrientDBSpec.scala:233)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
[info]   at org.scalatest.WordSpec.newAssertionFailedException(WordSpec.scala:1881)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
[info]   at akka.stream.alpakka.orientdb.OrientDBSpec.$anonfun$new$10(OrientDBSpec.scala:233)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
```

https://travis-ci.org/akka/alpakka/jobs/392950404

**Comment by ennru** [comment]
This hasn't been failing since the make-over for Alpakka 1.0.

**Comment by seglo** [comment]
https://travis-ci.com/github/akka/alpakka/jobs/479272634#L971
