### ISSUE TITLE
Failed: OrientDBSpec *** ABORTED ***

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1046]
```
[info] akka.stream.alpakka.orientdb.OrientDBSpec *** ABORTED *** (3 seconds, 472 milliseconds)
[info] 	DB name="GratefulDeadConcertsScala"
[info]   at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:295)
[info]   at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:450)
[info]   at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:314)
[info]   at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:269)
[info]   at akka.stream.alpakka.orientdb.OrientDBSpec.beforeAll(OrientDBSpec.scala:59)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.stream.alpakka.orientdb.OrientDBSpec.run(OrientDBSpec.scala:21)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:301)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:291)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: java.lang.NumberFormatException: For input string: "nothing"
[info]   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[info]   at java.lang.Integer.parseInt(Integer.java:580)
[info]   at java.lang.Integer.parseInt(Integer.java:615)
...
```

https://travis-ci.org/akka/alpakka/jobs/396448040

**Comment by 2m** [comment]
Looks like it started failing often: https://travis-ci.org/akka/alpakka/jobs/396728880

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/395939720

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/396996440
