### ISSUE TITLE
Failed: AmqpConnectorsSpec should declare connection that does not require server acks 

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1110]
```
[info] - should declare connection that does not require server acks *** FAILED *** (242 milliseconds)
[info]   The future returned an exception of type: com.rabbitmq.client.AlreadyClosedException, with message: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 1, class-id=60, method-id=80). (AmqpConnectorsSpec.scala:401)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.alpakka.amqp.scaladsl.AmqpConnectorsSpec.$anonfun$new$41(AmqpConnectorsSpec.scala:401)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

After https://github.com/akka/alpakka/pull/1001

**Comment by ennru** [comment]
This test is failing constantly on Travis. I tried to get the master-merge build through, but this keeps failing every time.
