### ISSUE TITLE
JmsProducer closes connection too late on external stream completion

### ISSUE THREAD

**Issue by andreas-schroeder** [akka/alpakka#1115]
I am currently running a `JmsProducer.flow` in a `akka.stream.scaladsl.RestartFlow` that externally triggers stage shutdown. While doing this, I randomly experienced issues on closing sessions and connections: the Docker containers providing my Jms broker mock were already gone before the connection was closed, even though I waited for the termination of the stream to complete.

The exception stack traces that happen are filling up our integration test logs on my console (Jms stack traces can be quite impressive), and also on our poor CI server :)

The test below reproduces the issue. 
Notes: 
- adding a delay before checking for session and connection closing makes the test pass.
- I am using old-school `synchronized` in the test to make sure changes to the three flags is properly propagated and made visible across threads.

If there's something I'm doing wrong, let me know!

```scala
import akka.actor.ActorSystem
import akka.stream.alpakka.jms.scaladsl.JmsProducer
import akka.stream.alpakka.jms.{JmsProducerSettings, JmsTextMessage}
import akka.stream.scaladsl.{Sink, Source}
import akka.stream.{ActorMaterializer, KillSwitches}
import javax.jms._
import org.mockito.ArgumentMatchers._
import org.mockito.Mockito._
import org.scalatest.mockito.MockitoSugar
import org.scalatest.{MustMatchers, WordSpec}

import scala.concurrent.Await
import scala.concurrent.duration._

class JmsProducerShutdownSpec extends WordSpec with MustMatchers with MockitoSugar {

  implicit val system: ActorSystem = ActorSystem("jms-test")
  implicit val mat: ActorMaterializer = ActorMaterializer()

  "JmsProducer shutdown" should {
    "close sessions and connection" in {
      for (_ <- 1 to 10) new Setup {
        val done =
            Source
              .repeat(new JmsTextMessage("hello jms!"))
              .wireTap(Sink.onComplete(_ => lock.synchronized(completionSignaled = true)))
              .via(JmsProducer.flow(JmsProducerSettings(factory).withQueue("test")))
              .via(kill.flow).runWith(Sink.ignore)

        kill.shutdown()

        Await.result(done, 1.second)

        while(!lock.synchronized(completionSignaled)) {
          // busy wait for completion to have propagated through the producer.
        }
        lock.synchronized {
          sessionClosed mustBe true // this one is good.
          connectionClosed mustBe true // but this is not.
        }
      }
    }
  }

  trait Setup {
    val factory = mock[ConnectionFactory]
    val connection = mock[Connection]
    val session = mock[Session]
    val producer = mock[MessageProducer]
    val textMessage = mock[TextMessage]
    val lock = new AnyRef
    var connectionClosed = false
    var sessionClosed = false
    var completionSignaled = false

    when(factory.createConnection()).thenReturn(connection)
    when(connection.createSession(anyBoolean(), anyInt())).thenReturn(session)
    when(session.createProducer(any[Destination])).thenReturn(producer)
    when(session.createTextMessage(anyString())).thenReturn(textMessage)

    when(connection.close()).thenAnswer { _ => lock.synchronized(connectionClosed = true) }
    when(session.close()).thenAnswer { _ => lock.synchronized(sessionClosed = true) }

    val kill = KillSwitches.shared("jms")
  }
}
```

**Comment by 2m** [comment]
After taking a look at the JMS conector, I see that in some places the `close` method on connection is called asynchronously as a completion callback on various futures. That means that there is no guarantee that `close` will be called before the completion is being signaled. 

I think this is what you have seen as well, by adding a sleep before

```scala
sessionClosed mustBe true // this one is good.
connectionClosed mustBe true // but this is not.
```

which has made the test pass.

What were the exceptions that you have noticed in your CI logs? Are these exceptions that are being thrown while calling `close` on already terminated connections?

**Comment by andreas-schroeder** [comment]
Hi @2m, here's some nice an long stack trace (with some original German text for flavor). Basically, it says that while trying to close the connection, it got some connectivity issue with the docker host running on localhost (because that one is already shutting down)

```
[ERROR] [08/14/2018 12:44:01.053] [tsr-downstream-dispatcher-akka.stream.default-blocking-io-dispatcher-36] [akka://tsr-downstream-dispatcher/system/StreamSupervisor-0/flow-9-4-unnamed] Error during postStop in [akka.stream.alpakka.jms.JmsProducerStage@4e60e2de]: JMSWMQ2003: Fehler beim Schließen von Thema 'dev/'.
com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ2003: Fehler beim Schließen von Thema 'dev/'.
JMS versuchte, eine IBM MQ-Zieladresse zu schließen, es ist jedoch ein Fehler aufgetreten. Die Zieladresse wurde möglicherweise bereits geschlossen oder ein anderer Thread führt einen MQGET-Aufruf aus, während close() aufgerufen wird.
Ermitteln Sie die Ursache dieses Fehlers mithilfe der verlinkten Ausnahmebedingung. Sie können den Schließvorgang (close()) möglicherweise zu einem späteren Zeitpunkt ausführen.
	at com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1263)
	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$500(WMQMessageProducer.java:75)
	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:739)
	at com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1308)
	at com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
	at com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:584)
	at com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:349)
	at com.ibm.mq.jms.MQSession.close(MQSession.java:275)
	at akka.stream.alpakka.jms.JmsSession.closeSession(JmsConnector.scala:99)
	at akka.stream.alpakka.jms.JmsProducerStage$$anon$1.$anonfun$postStop$1(JmsProducerStage.scala:141)
	at akka.stream.alpakka.jms.JmsProducerStage$$anon$1.$anonfun$postStop$1$adapted(JmsProducerStage.scala:141)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at akka.stream.alpakka.jms.JmsProducerStage$$anon$1.postStop(JmsProducerStage.scala:141)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:382)
	at akka.stream.impl.fusing.GraphInterpreterShell.tryAbort(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1(ActorGraphInterpreter.scala:797)
	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1$adapted(ActorGraphInterpreter.scala:797)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at akka.stream.impl.fusing.ActorGraphInterpreter.postStop(ActorGraphInterpreter.scala:797)
	at akka.actor.Actor.aroundPostStop(Actor.scala:536)
	at akka.actor.Actor.aroundPostStop$(Actor.scala:536)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPostStop(ActorGraphInterpreter.scala:670)
	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:210)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:172)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:142)
	at akka.actor.ActorCell.terminate(ActorCell.scala:431)
	at akka.actor.ActorCell.invokeAll$1_aroundBody2(ActorCell.scala:529)
	at akka.actor.ActorCell$AjcClosure3.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation.$anonfun$aroundSystemMessageInvoke$1(ActorSystemMessageInstrumentation.scala:36)
	at kamon.Kamon$.withContext(Kamon.scala:120)
	at akka.kamon.instrumentation.ActorSystemMessageInstrumentation.aroundSystemMessageInvoke(ActorSystemMessageInstrumentation.scala:36)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:515)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.ibm.mq.MQException: JMSCMQ0001: Der IBM MQ-Aufruf ist mit Beendigungscode '2' ('MQCC_FAILED') und Ursache '2009' ('MQRC_CONNECTION_BROKEN') fehlgeschlagen.
	at com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
	... 46 more
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
	at com.ibm.mq.jmqi.remote.impl.RemoteSession.receiveAsyncTsh(RemoteSession.java:632)
	at com.ibm.mq.jmqi.remote.impl.RemoteSession.receiveTSH(RemoteSession.java:812)
	at com.ibm.mq.jmqi.remote.impl.RemoteSession.receiveMQIFlow(RemoteSession.java:1458)
	at com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:7883)
	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:588)
	at com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
	at com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:713)
	... 43 more
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
	at com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3663)
	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:547)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
	at com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
	at com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
	at com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
Caused by: com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Fehler beim Empfang von Host '/127.0.0.1:65403 (localhost)'. [1=-1,2=ffffffff,3=/127.0.0.1:65403 (localhost),4=TCP]
	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:758)
	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:699)
	at com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:139)
	... 5 more
```

**Comment by ennru** [comment]
@andreas-schroeder is this still a problem with all the work you put into Alpakka JMS?

**Comment by andreas-schroeder** [comment]
@ennru with the new connectivity status info, it is now possible to wait for the connection being closed. So I think you are right, we can close this one.
