### ISSUE TITLE
failed: MqttSourceSpec

### ISSUE THREAD

**Issue by patriknw** [akka/alpakka#127]
This is failing a lot:

```
[info] - should receive a message from a topic with right credentials *** FAILED *** (3 seconds, 453 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 3 seconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:291)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:282)
[info]   at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:682)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$13$$anonfun$apply$14.apply(MqttSourceSpec.scala:133)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$13$$anonfun$apply$14.apply(MqttSourceSpec.scala:131)
[info]   at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:677)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec.whenReady(MqttSourceSpec.scala:25)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$13.apply(MqttSourceSpec.scala:131)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anonfun$apply$13.apply(MqttSourceSpec.scala:125)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec.withBroker(MqttSourceSpec.scala:226)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(MqttSourceSpec.scala:125)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(MqttSourceSpec.scala:125)
```

https://travis-ci.org/akka/alpakka/jobs/185785246

**Comment by filosganga** [comment]
My PR #112 may be able to fix it.

**Comment by filosganga** [comment]
Not it does not and I am experiencing the same issue randomly. I think @2m was right and the best option will be using docker. But to do that we need a native way to push messages to the mosquitto server as the tests rely on that at the moment.

**Comment by 2m** [comment]
I think I'll add MqttSink. It will help move broker to docker but is also
generally usable.

2016-12-25, sk 22:08, Filippo De Luca <notifications@github.com> rašė:

**Comment by 2m** [comment]
#131 moves away from the in memory broker
