### ISSUE TITLE
Exception when parsing S3Exception after attempt to download file metadata

### ISSUE THREAD

**Issue by samuelsayag** [akka/alpakka#1281]
Hi using the S3Connector I had an exception when downloading metadata of a file and receiving a Success("") from AWS.

Received this with **1.0-M1**: 
```
[error] Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
[error]         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
[error]         at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[error]         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error]         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error]         at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
[error]         at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
[error]         at scala.xml.XML$.loadXML(XML.scala:58)
[error]         at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
[error]         at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
[error]         at scala.xml.XML$.loadString(XML.scala:58)
[error]         at akka.stream.alpakka.s3.S3Exception.<init>(S3Exception.scala:18)
[error]         at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$getObjectMetadata$6(S3Stream.scala:152)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error]         at scala.util.Success.map(Try.scala:209)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
[error]         at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
[error]         at scala.concurrent.Future.map(Future.scala:288)
[error]         at scala.concurrent.Future.map$(Future.scala:288)
[error]         at akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
[error]         at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$getObjectMetadata$3(S3Stream.scala:151)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error]         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error]         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
[error]         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[error]         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
[error]         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
[error]         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error]         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[error]         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error]         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
I put a breakpoint where the S3Exception is initialized and it received an empty String. If it is considered xml systematically as it cannot parse it I guess.
Is it a bug ?
many thanks

**Comment by samuelsayag** [comment]
Yes I am sorry. I search for similar issue though but haven't seen it.
I close.
