### ISSUE TITLE
Failed MqttFlowSpec mqtt server flow should receive a bidirectional connection and a subscription to a topic 

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1295]
https://travis-ci.org/akka/alpakka/jobs/447443837

```
[info] MqttFlowSpec:
[info] mqtt client flow
[info] - should establish a bidirectional connection and subscribe to a topic (224 milliseconds)
[info] mqtt server flow
[info] - should receive a bidirectional connection and a subscription to a topic *** FAILED *** (216 milliseconds)
[info]   Unexpected event: Right(Event(PubAck(PacketId(1)),None)) (MqttFlowSpec.scala:140)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
[info]   at docs.scaladsl.MqttFlowSpec.newAssertionFailedException(MqttFlowSpec.scala:20)
[info]   at org.scalatest.Assertions$class.fail(Assertions.scala:1089)
[info]   at docs.scaladsl.MqttFlowSpec.fail(MqttFlowSpec.scala:20)
[info]   at docs.scaladsl.MqttFlowSpec$$anonfun$2$$anonfun$apply$mcV$sp$2.apply(MqttFlowSpec.scala:140)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
```

**Comment by huntc** [comment]
Thanks. I shall look at this first thing.
