### ISSUE TITLE
Failure: JmsConnector connection status should reflect connection status on connection retries

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1306]
```
[info] - should reflect connection status on connection retries *** FAILED *** (16 seconds, 792 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 16 times over 10.034311338 seconds. Last failure message: Published connection state Disconnected was not Connected. (JmsConnectionStatusSpec.scala:349)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
[info]   at akka.stream.alpakka.jms.JmsSpec.eventually(JmsSpec.scala:18)
[info]   at akka.stream.alpakka.jms.JmsConnectionStatusSpec.$anonfun$new$43(JmsConnectionStatusSpec.scala:349)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
[info]   at akka.stream.alpakka.jms.JmsConnectionStatusSpec.$anonfun$new$42(JmsConnectionStatusSpec.scala:348)
[info]   at akka.stream.alpakka.jms.JmsConnectionStatusSpec.$anonfun$new$42$adapted(JmsConnectionStatusSpec.scala:313)
[info]   at akka.stream.alpakka.jms.JmsSpec.withServer(JmsSpec.scala:54)
[info]   at akka.stream.alpakka.jms.JmsConnectionStatusSpec.$anonfun$new$41(JmsConnectionStatusSpec.scala:313)
```

https://travis-ci.org/akka/alpakka/jobs/451313850

**Comment by ennru** [comment]
A different variant in the same test:

```
[info] JmsConnectionStatusSpec:
[info] JmsConnector connection status
[info] - should reflect connection status on connection retries *** FAILED *** (3 seconds, 916 milliseconds)
[info]   java.io.IOException: VMTransportServer already bound at: vm://brokerName-a6671ba7-3b6c-4aca-a52e-b1dc55936cc9?create=false
```

https://travis-ci.org/akka/alpakka/jobs/492957863#L706

**Comment by 2m** [comment]
```
[info] - should reflect connection status on connection retries *** FAILED *** (2 seconds, 133 milliseconds)
[info]   java.io.IOException: VMTransportServer already bound at: vm://brokerName-f83bdfce-c8c3-49af-bafc-5eb4da36b8e5?create=false
[info]   at org.apache.activemq.transport.vm.VMTransportFactory.bind(VMTransportFactory.java:237)
[info]   at org.apache.activemq.transport.vm.VMTransportFactory.doBind(VMTransportFactory.java:223)
[info]   at org.apache.activemq.transport.TransportFactorySupport.bind(TransportFactorySupport.java:40)
[info]   at org.apache.activemq.broker.TransportConnector.createTransportServer(TransportConnector.java:318)
[info]   at org.apache.activemq.broker.TransportConnector.getServer(TransportConnector.java:141)
```

https://travis-ci.com/akka/alpakka/jobs/192800923

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/208998412

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/226263585

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/260963203#L1033 in #1347
