### ISSUE TITLE
Failed: AvroParquetSinkTest.createNewParquetFile

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1316]
```
[info] Test docs.javadsl.AvroParquetSinkTest.createNewParquetFile started
[error] Test docs.javadsl.AvroParquetSinkTest.createNewParquetFile failed: java.lang.RuntimeException: file:/home/travis/build/akka/alpakka/javaTestFolder/test.parquet is not a Parquet file (too small length: 0), took 4.232 sec
[error]     at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:514)
[error]     at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:689)
[error]     at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:595)
[error]     at org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:152)
[error]     at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
[error]     at docs.javadsl.AvroParquetSinkTest.checkResponse(AvroParquetSinkTest.java:98)
[error]     at docs.javadsl.AvroParquetSinkTest.createNewParquetFile(AvroParquetSinkTest.java:85)
```

https://travis-ci.org/akka/alpakka/jobs/452489678

**Comment by ennru** [comment]
Resolved by #1319
