### ISSUE TITLE
Failed: docs.javadsl.SqsPublishTest.sendMessageWithBatchesAsFlow

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1360]
```
[error] Test docs.javadsl.SqsPublishTest.sendMessageWithBatchesAsFlow failed: java.util.concurrent.TimeoutException: null, took 2.25 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.package$.blocking(package.scala:142)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at docs.javadsl.SqsPublishTest.sendMessageWithBatchesAsFlow(SqsPublishTest.java:253)
...
```

https://travis-ci.org/akka/alpakka/jobs/462223196

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/479853147

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/483188726

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/483908250

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/486971710

**Comment by ennru** [comment]
https://travis-ci.org/akka/alpakka/jobs/491569281#L616

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/491602012

**Comment by ennru** [comment]
This hasn't surfaced since over a year.
Closing.
