### ISSUE TITLE
S3: check if bucket exists before uploading object

### ISSUE THREAD

**Issue by neowulf33** [akka/alpakka#139]
When the bucket doesn't exist - the following error message isn't exactly helpful:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AuthorizationHeaderMalformed</Code>
<Message>
The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-east-1'
</Message><Region>us-east-1</Region><RequestId>5D40B7B86658B1FC</RequestId><HostId>KiBjtick/gvLkwKJO8f+2YeMe50asXa47XB5m9UeNCZMnwdG4M23oL1lzZuRc6Rw2iHrxAHtaww=</HostId></Error>
```

**Comment by francisdb** [comment]
@neowulf33 could you provide example code to reproduce this? Sounds like an old bug that might not be there any more

We should probably add a Get bucket info call returning an Option that would allow you to add the check in your code. Don't think this is something alpakka should be doing for every upload.

**Comment by francisdb** [comment]
I just tried this and depending on the access method / operation you get the below responses

So the reported error is not observed but error handling could be cleaned up, S3Exception everywhere and where possible a proper non-xml message.

```
akka.stream.alpakka.s3.S3Exception: The specified bucket does not exist
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$entityForSuccess$1(S3Stream.scala:327)
```

```
Cause: akka.stream.alpakka.s3.S3Exception: Access Denied
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$entityForSuccess$1(S3Stream.scala:327)
```

```
java.lang.RuntimeException: Got 404 Not Found for DELETE my-test-us-east-1 putTest
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$deleteObject$3(S3Stream.scala:132)
```

```
java.lang.Exception: Can't initiate upload: <?xml version="1.0" encoding="UTF-8"?>
[info] <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>my-test-us-east-1</BucketName><RequestId>1FE5BE240E7CC61E</RequestId><HostId>xxx</HostId></Error>
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$initiateMultipartUpload$4(S3Stream.scala:195)
```

```
java.lang.Exception: Can't initiate upload: <?xml version="1.0" encoding="UTF-8"?>
[info] <Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>my-test-us-east-1</BucketName><RequestId>C467DB5F775A9AC9</RequestId><HostId>xxx</HostId></Error>
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$initiateMultipartUpload$4(S3Stream.scala:195)
```

```
java.lang.Exception: Can't initiate upload: <?xml version="1.0" encoding="UTF-8"?>
[info] <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>E0EB9D2958A3C6C1</RequestId><HostId>xxx</HostId></Error>
[info]   at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$initiateMultipartUpload$4(S3Stream.scala:195)
```
