### ISSUE TITLE
S3: multipart upload to new buckets fails with Unsupported Content-Type

### ISSUE THREAD

**Issue by m3nadav** [akka/alpakka#142]
```
Caused by: akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/octet-stream
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:155) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:111) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$22$$anonfun$apply$23.apply(Unmarshaller.scala:108) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$16$$anonfun$apply$17.apply(Unmarshaller.scala:88) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:55) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:19) ~[akka-http-experimental_2.11-2.4.11.jar:?]
	at akka.stream.alpakka.s3.impl.S3Stream$$anonfun$akka$stream$alpakka$s3$impl$S3Stream$$initiateMultipartUpload$1.apply(S3Stream.scala:86) ~[akka-stream-alpakka-s3_2.11-0.3.jar:0.3]
	at akka.stream.alpakka.s3.impl.S3Stream$$anonfun$akka$stream$alpakka$s3$impl$S3Stream$$initiateMultipartUpload$1.apply(S3Stream.scala:85) ~[akka-stream-alpakka-s3_2.11-0.3.jar:0.3]
...
```

When creating a new s3 bucket, Amazon's DNS servers need to update the new records so one can use the following REST API host
`https://bucket_name.s3.amazonaws.com`
Untill then, that generic API host will respond with code 307-[[TemporaryRedirect](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)] (which has no Unmarshaller) to a region-specific host 
`https://bucket_name.s3-REGION.amazonaws.com`

There are two ways to solve this - handling redirects or using region-specific requests.
I'm about to submit a PR that uses region-specific requests

**Comment by abelbryo** [comment]
I keep getting the same error and I am using version `0.11`
```
akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/octet-stream
        at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:158)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:114)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:111)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$18$$anonfun$apply$19.apply(Unmarshaller.scala:91)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$18$$anonfun$apply$19.apply(Unmarshaller.scala:91)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)
        at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
```

**Comment by mikesname** [comment]
@abelbryo  Also seeing this error on `0.11`, but, seemingly, only when my bucket region didn't match that set on the multipart upload sink - maybe something to check?

**Comment by abelbryo** [comment]
@mikesname Thanks for the reply. I have only one region `us-east-1` and it is not obvious to me how you can "set" the region on the multipart upload sink. Here is the code as found in the spec. Also, downloading and list bucket operations work. Only upload seems to be the issue.

```val sink = client.multipartUpload(bucket, key, metaHeaders = MetaHeaders(metaHeaders))```

**Comment by l15k4** [comment]
I have this too on https://github.com/jubos/fake-s3 . I upgraded to `0.16` because it has support for setting `endpointUrl` and `pathStyleAccess` #677 which should allow for using `fake-s3` but unfortunately it doesn't work for the multipart upload.
