### ISSUE TITLE
Failed: Mqtt-Streaming server connector should re-connect given connect, subscribe, connect again, publish

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1469]
Has been failing on Travis CI.

```
[info] - should re-connect given connect, subscribe, connect again, publish *** FAILED *** (3 seconds, 142 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ByteString(32, 2, 0, 0)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at docs.scaladsl.MqttSessionSpec$$anonfun$2.docs$scaladsl$MqttSessionSpec$$anonfun$$reconnectTest$1(MqttSessionSpec.scala:1549)
[info]   at docs.scaladsl.MqttSessionSpec$$anonfun$2$$anonfun$apply$mcV$sp$5.apply$mcV$sp(MqttSessionSpec.scala:1566)
[info]   at docs.scaladsl.MqttSessionSpec$$anonfun$2$$anonfun$apply$mcV$sp$5.apply(MqttSessionSpec.scala:1566)
[info]   at docs.scaladsl.MqttSessionSpec$$anonfun$2$$anonfun$apply$mcV$sp$5.apply(MqttSessionSpec.scala:1566)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

https://travis-ci.org/akka/alpakka/jobs/486625093

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/487365076

**Comment by huntc** [comment]
I'm not sure why this test fails. All I can think of is that CI is slow given that it is an integration test style 
 of thing... Have we increased the test dilation in general?

Please add to this issue if the issue continues.

**Comment by ennru** [comment]
This hasn't shown for almost a year.
Closing.
