### ISSUE TITLE
S3 download not working in M2 but works fine in M1

### ISSUE THREAD

**Issue by denisgarci** [akka/alpakka#1522]
### Versions used 
Alpakka version: 1.0-M2 
Akka version: 2.5.21

### Expected Behavior
I ported some Akka Stream code from Alpakka 1.0-M1 to  Alpakka 1.0-M2. In M2, `S3.download` doesn't work anymore. I'm using the same S3 settings in both versions. `S3.listBucket` works fine with M2 and M1.

### Actual Behavior
I get the following error
```
[ERROR] [02/21/2019 10:24:40.781] [default-akka.actor.default-dispatcher-2] [akka.stream.Log(akka://default/system/StreamSupervisor-0)] [download] Upstream failed.
akka.stream.alpakka.s3.S3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (Code: PermanentRedirect, RequestID: , HostID: )
	at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$entityForSuccess$1(S3Stream.scala:555)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [02/21/2019 10:24:40.802] [default-akka.actor.default-dispatcher-16] [akka.actor.ActorSystemImpl(default)] Outgoing request stream error (akka.stream.AbruptTerminationException: Processor actor [Actor[akka://default/system/StreamSupervisor-1/flow-3-0-PoolFlow#1755679542]] terminated abruptly)
```

**Comment by denisgarci** [comment]
Already fixed in https://github.com/akka/alpakka/pull/1444
