### ISSUE TITLE
Failed: SqsAckSpec aborted

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1550]
```
[info] - should ignore batch of messages (8 milliseconds)
[info] docs.scaladsl.SqsAckSpec *** ABORTED *** (10 seconds, 168 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:157)
[info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.ready(package.scala:169)
[info]   at akka.stream.alpakka.sqs.scaladsl.DefaultTestContext$class.afterAll(DefaultTestContext.scala:63)
[info]   at docs.scaladsl.SqsAckSpec.afterAll(SqsAckSpec.scala:25)
[info]   at org.scalatest.BeforeAndAfterAll$$anonfun$1.apply$mcV$sp(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:379)
[info]   at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:375)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
[info]   at org.scalatest.Status$class.withAfterEffect(Status.scala:375)
[info]   at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:782)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:223)
```

https://travis-ci.org/akka/alpakka/jobs/500172931

**Comment by ennru** [comment]
This hasn't surfaced since over a year.
Closing.
