### ISSUE TITLE
Cannot create Producer/Consummer settings

### ISSUE THREAD

**Issue by politrons** [akka/alpakka#1601]
Hi all,

Since I upfate to the latest version of Akka-stream-kafka  I receive an exception when I create a ConsumerSettings or ProducerSettings

**ProducerSettings**
```
  val producerIntSettings: ProducerSettings[Array[Byte], Integer] = ProducerSettings(system, new ByteArraySerializer, new IntegerSerializer)
    .withBootstrapServers(bootstrapServers)
```
**ConsumerSettings**
`    var consumerSettings = ConsumerSettings.create(actorSystem, new ByteArrayDeserializer(), new ByteArrayDeserializer())`
```
In the migration guide there´s no mention about this issue

An exception or error caused a run to abort: akka.util.JavaDurationConverters$JavaDurationOps$.asScala$extension(Ljava/time/Duration;)Lscala/concurrent/duration/FiniteDuration; 
java.lang.NoSuchMethodError: akka.util.JavaDurationConverters$JavaDurationOps$.asScala$extension(Ljava/time/Duration;)Lscala/concurrent/duration/FiniteDuration;
	at akka.kafka.ProducerSettings$.apply(ProducerSettings.scala:59)
	at akka.kafka.ProducerSettings$.apply(ProducerSettings.scala:36)
	at akka.kafka.ProducerSettings$.apply(ProducerSettings.scala:83)
	at com.ingdirect.es.asyncmessage.kafka.stream.KafkaSourceIntegration.<init>(KafkaSourceIntegration.scala:322)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1422)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1236)
	at org.scalatest.tools.Runner$$$Lambda$73/2032188048.apply(Unknown Source)
	at scala.collection.immutable.List.map(List.scala:286)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1235)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$$$Lambda$63/1291113768.apply(Unknown Source)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at 
```org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)

**Comment by ennru** [comment]
What Akka version are you on?

**Comment by politrons** [comment]
We´re using the 2.5.9 of Actor system, unfortunately I cannot upgrade to the 2.5.21 actor library that internally the library use.
For now to solve the problem of Wakeup exceptions issues I use the pattern of Error Handling that was already defined in the 0.22

https://doc.akka.io/docs/akka-stream-kafka/0.22/errorhandling.html

Using this pattern we control all possible unhandled exceptions, and we will recreate the connector forever right?   

Regards

**Comment by ennru** [comment]
> We´re using the 2.5.9 of Actor system, unfortunately I cannot upgrade to the 2.5.21 actor library that internally the library use.

Do you have an identified reason for that? Akka 2.5.21 is binary compatible with 2.5.9, but some source changes might be required.

See https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#binary-compatibility-rules

> For now to solve the problem of Wakeup exceptions issues I use the pattern of Error Handling that was already defined in the 0.22
> 
> [doc.akka.io/docs/akka-stream-kafka/0.22/errorhandling.html](https://doc.akka.io/docs/akka-stream-kafka/0.22/errorhandling.html)
> 
> Using this pattern we control all possible unhandled exceptions, and we will recreate the Consumer forever right?

Yes.

**Comment by politrons** [comment]
Thanks for the answer.
We cannot afford the risk to upgrade the Akka actor version, we´re in production already and we experiment in the pass in another project that move from the 2.5.9 to 2.5.17 was not 100% retro compatible, and some extra dependencies were mandatory.

We will upgrade in a future with enough time to test everything properly.

For now if the workaround of the Error handling is secure enough to avoid the dead of the Connector it´s enough

Regards.

**Comment by ennru** [comment]
Ok, I'll close this than.
