### ISSUE TITLE
Google cloud pubsub error with akka-http 10.1.8

### ISSUE THREAD

**Issue by yanns** [akka/alpakka#1610]
### Versions used 
Alpakka version: 0.20
"akka-stream-alpakka-google-cloud-pub-sub" % "0.20" 

Akka version: 2.5.21
Akka-http version: 10.1.8

### Actual Behavior

The application fails to start with the following error:
```
[ERROR] Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.5.21 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.
[ERROR] Uncaught error from thread [pim-indexer-akka.actor.default-dispatcher-2]: akka.http.scaladsl.model.MediaTypes$.application$divx$minuswww$minusform$minusurlencoded()Lakka/http/scaladsl/model/MediaType$WithOpenCharset;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[pim-indexer]
[ERROR] java.lang.NoSuchMethodError: akka.http.scaladsl.model.MediaTypes$.application$divx$minuswww$minusform$minusurlencoded()Lakka/http/scaladsl/model/MediaType$WithOpenCharset;
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.HttpApi.getAccessToken(HttpApi.scala:144)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.HttpApi.getAccessToken$(HttpApi.scala:135)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.HttpApi$.getAccessToken(HttpApi.scala:30)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.Session.getNewToken(Session.scala:22)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.Session.$anonfun$getToken$1(Session.scala:33)
[ERROR] 	at scala.Option.getOrElse(Option.scala:138)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.Session.getToken(Session.scala:33)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.GooglePubSubSource$$anon$1.akka$stream$alpakka$googlecloud$pubsub$GooglePubSubSource$$anon$$fetch(GooglePubSubSource.scala:39)
[ERROR] 	at akka.stream.alpakka.googlecloud.pubsub.GooglePubSubSource$$anon$1$$anon$2.onPull(GooglePubSubSource.scala:80)
[ERROR] 	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:522)
[ERROR] 	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:418)
[ERROR] 	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
[ERROR] 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:558)
[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:664)
[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.finishShellRegistration(ActorGraphInterpreter.scala:706)
[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:721)
[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:714)
[ERROR] 	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
[ERROR] 	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
[ERROR] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:655)
[ERROR] 	at akka.actor.ActorCell.create(ActorCell.scala:656)
[ERROR] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:527)
[ERROR] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:549)
[ERROR] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
[ERROR] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[ERROR] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
[ERROR] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[ERROR] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[ERROR] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[ERROR] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by yanns** [comment]
Just missed the version "akka-stream-alpakka-google-cloud-pub-sub" % "1.0-RC1"
Sorry for the noise.
