### ISSUE TITLE
Alpakka SQS 1.0.0 incompatible with akka-http 10.1.8 - SdkClientException in SqsSource

### ISSUE THREAD

**Issue by kevinmehall** [akka/alpakka#1645]
akka-http 10.1.8 contains a [change to the x-www-form-urlencoded content-type](https://github.com/akka/akka-http/pull/2402), which breaks code in Alpakka's dependency `aws-spi-akka-http` that matches on a `content-type` string. This was fixed [there](https://github.com/matsluni/aws-spi-akka-http/commit/25cf57c4bf9404d36b46d10fef509ffbad008a48) in 0.0.5 and the dependency in Alpakka was [already updated for unrelated reasons](https://github.com/akka/alpakka/commit/7f5a70f12a4b7b42eef1eae746949d998bf557a4). I think this means it's already fixed on Alpakka's master branch, but I wanted to open an issue to make this more searchable if anyone else is encountering this issue.

### Versions used 

Alpakka SQS 1.0.0
Akka 2.5.22
Akka-HTTP 10.1.8
aws-spi-akka-http 0.0.4

### Expected Behavior

`SqsSource` is able to retrieve messages from SQS when another dependency pulls in the latest patch release of Akka-HTTP.

### Actual Behavior

Attempts to run the source fail with an exception:

```
software.amazon.awssdk.core.exception.SdkClientException
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
	at software.amazon.awssdk.core.internal.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:209)
	at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler.invoke(BaseAsyncClientHandler.java:181)
	at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:123)
	at software.amazon.awssdk.core.client.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:68)
	at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:51)
	at software.amazon.awssdk.services.sqs.DefaultSqsAsyncClient.receiveMessage(DefaultSqsAsyncClient.java:1120)
	at akka.stream.alpakka.sqs.scaladsl.SqsSource$.$anonfun$apply$4(SqsSource.scala:45)
	at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1373)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:480)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:599)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:569)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:675)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:724)
	at akka.actor.Actor.aroundPreStart(Actor.scala:550)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:550)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:664)
	at akka.actor.ActorCell.create(ActorCell.scala:674)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:545)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:567)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.github.matsluni.akkahttpspi.AkkaHttpClient.tryCreateCustomContentType(AkkaHttpClient.scala:110)
	at com.github.matsluni.akkahttpspi.AkkaHttpClient.contentTypeHeaderToContentType(AkkaHttpClient.scala:88)
	at com.github.matsluni.akkahttpspi.AkkaHttpClient.toAkkaRequest(AkkaHttpClient.scala:60)
	at com.github.matsluni.akkahttpspi.AkkaHttpClient.execute(AkkaHttpClient.scala:47)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.executeHttpRequest(MakeAsyncHttpRequestStage.java:117)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.doExecute(AsyncRetryableStage.java:203)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:104)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.execute(AsyncRetryableStage.java:99)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:75)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:29)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.execute(AsyncApiCallTimeoutTrackingStage.java:61)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.execute(AsyncApiCallTimeoutTrackingStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.AmazonAsyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonAsyncHttpClient.java:207)
	... 27 more
```

**Comment by pwheimann** [comment]
I actually think this error isn't related or entirely related to the Akka HTTP 10.1.8 upgrade...

I believe the java.lang.ArrayIndexOutOfBoundsException is fixed in here - 
https://github.com/matsluni/aws-spi-akka-http/commit/10abfc8118836e1f54a67aeb4ab8d139c7d2171a#diff-bda38d5912e3083a43049ebda8dc0b75L110

I had to use a dependency override in my build.sbt to fix this - 

dependencyOverrides += "com.github.matsluni" %% "aws-spi-akka-http" % "0.0.5"

**Comment by 2m** [comment]
Thanks for the ticket and additional investigation.

The upgrade to the latest aws-spi-akka-http has been merged and snapshot artifacts have been published. You can try it out by following instructions from the [snapshots page](https://doc.akka.io/docs/alpakka/current/other-docs/snapshots.html).
