### ISSUE TITLE
Failed: UnixDomainSocketSpec should not be able to connect to a non-existent file

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1649]
```
[info] - should not be able to connect to a non-existent file *** FAILED *** (14 milliseconds)
[info]   scala.MatchError: java.util.NoSuchElementException: head of empty stream (of class java.util.NoSuchElementException)
[info]   at docs.scaladsl.UnixDomainSocketSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$15.apply(UnixDomainSocketSpec.scala:177)
[info]   at docs.scaladsl.UnixDomainSocketSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anonfun$apply$15.apply(UnixDomainSocketSpec.scala:177)
[info]   at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
[info]   at scala.util.Try$.apply(Try.scala:192)
[info]   at scala.util.Success.map(Try.scala:237)
[info]   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[info]   at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
[info]   at org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
```

https://travis-ci.com/akka/alpakka/jobs/192800945#L869

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/197199565

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/198867107

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/199906903

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/201036061

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/200518681

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/205945075#L614

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/208998431

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/212966921

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/226263604

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/254015144#L413

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/254122676#L511

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/260163611#L499

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/259855789#L426 in #2006

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/271383980#L378

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/275777751#L480

**Comment by ennru** [comment]
https://travis-ci.com/github/akka/alpakka/jobs/298820291#L770 in master

**Comment by ennru** [comment]
Slightly different failure

```
[info] - should not be able to connect to a non-existent file *** FAILED *** (65 milliseconds)
[info]   The future returned an exception of type: java.util.NoSuchElementException, with message: Future.failed not completed with a throwable.. (UnixDomainSocketSpec.scala:180)

[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at docs.scaladsl.UnixDomainSocketSpec.$anonfun$new$20(UnixDomainSocketSpec.scala:180)
```

https://travis-ci.com/github/akka/alpakka/jobs/387994244#L678
