### ISSUE TITLE
Failed JmsConnectorsSpec should producer disconnect exceptional completion

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1716]
```
[info] - should producer disconnect exceptional completion *** FAILED *** (2 minutes)
[info]   A timeout occurred waiting for a future to complete. Queried 1996 times, sleeping 60 milliseconds between each query. (JmsConnectorsSpec.scala:584)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at docs.scaladsl.JmsConnectorsSpec.$anonfun$new$60(JmsConnectorsSpec.scala:584)
[info]   at docs.scaladsl.JmsConnectorsSpec.$anonfun$new$60$adapted(JmsConnectorsSpec.scala:561)
[info]   at akka.stream.alpakka.jms.JmsSpec.withServer(JmsSpec.scala:50)
[info]   at docs.scaladsl.JmsConnectorsSpec.$anonfun$new$59(JmsConnectorsSpec.scala:561)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

https://travis-ci.com/akka/alpakka/jobs/200518662

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/223291792

**Comment by ennru** [comment]
This hasn't surfaced since over a year.
Closing.
