### ISSUE TITLE
Failed: EventSourceSpec should read gzipped replies

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1735]
```
[info] - should read gzipped replies *** FAILED *** (8 milliseconds)
[info]   java.net.BindException: Cannot assign requested address
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:433)
[info]   at sun.nio.ch.Net.bind(Net.java:425)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
```

https://travis-ci.com/akka/alpakka/jobs/203473870

**Comment by 2m** [comment]
https://travis-ci.com/akka/alpakka/jobs/223291808

**Comment by ennru** [comment]
This hasn't surfaced since over a year.
Closing.
