### ISSUE TITLE
[FAILED] FtpIOSource should retrieve a bigger file (~2 MB) from path as a stream of bytes

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#185]
```
[info] - should retrieve a bigger file (~2 MB) from path as a stream of bytes *** FAILED *** (3 seconds, 249 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 300 milliseconds between each query. (CommonFtpSourceSpec.scala:66)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[infom]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.alpakka.ftp.CommonFtpSourceSpec.$anonfun$$init$$6(CommonFtpSourceSpec.scala:66)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.stream.alpakka.ftp.SftpSourceSpec.withFixture(CommonFtpSourceSpec.scala:13)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[info]   at akka.stream.alpakka.ftp.SftpSourceSpec.org$scalatest$BeforeAndAfter$$super$runTest(CommonFtpSourceSpec.scala:13)
[info]   at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
[info]   at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
[info]   at akka.stream.alpakka.ftp.SftpSourceSpec.runTest(CommonFtpSourceSpec.scala:13)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
```

**Comment by patriknw** [comment]
@2m Isn't this fixed via https://github.com/akka/alpakka/commit/aaf738000ae4c1b77807cb22d13dffed65101fa8 ?

**Comment by 2m** [comment]
I see. Then the validation failure of the #147 was because it was not rebased on top of that fix. Closing this then.
