### ISSUE TITLE
JmsConnectorsSpec should only fail after maxBackoff retry

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#1897]
```
[info] - should only fail after maxBackoff retry *** FAILED *** (2 seconds, 751 milliseconds)
[info]   2732 was not greater than 3000 (JmsConnectorsSpec.scala:757)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6956)
[info]   at docs.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$20$$anonfun$apply$mcV$sp$49.apply(JmsConnectorsSpec.scala:757)
[info]   at docs.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$20$$anonfun$apply$mcV$sp$49.apply(JmsConnectorsSpec.scala:744)
[info]   at akka.stream.alpakka.jms.JmsSpec.withServer(JmsSpec.scala:50)
[info]   at docs.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$20.apply$mcV$sp(JmsConnectorsSpec.scala:744)
[info]   at docs.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$20.apply(JmsConnectorsSpec.scala:744)
[info]   at docs.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$20.apply(JmsConnectorsSpec.scala:744)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

https://travis-ci.com/akka/alpakka/jobs/226368965

**Comment by ennru** [comment]
I just verified this test runs on Travis, but we haven't logged any failure since this initial report.
https://travis-ci.com/github/akka/alpakka/jobs/384614166#L562

Closing.
