### ISSUE TITLE
AMQP: AmqpCachedConnectionProvider is not thread safe

### ISSUE THREAD

**Issue by marq** [akka/alpakka#1912]
AmqpCachedConnectionProvider is not thread safe. It is not stated anywhere it is but looking at the implementation (`AtomicReference`) it should be, right?

### Versions used 

Alpakka version: 1.1.1
Scala version: 2.12.9

### Reproducible Test Case

```scala
package rabbitmqtest

import akka.stream.alpakka.amqp.{AmqpCachedConnectionProvider, AmqpLocalConnectionProvider}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

object RabbitTest {

	def main(args: Array[String]): Unit = {
		val provider = AmqpCachedConnectionProvider(AmqpLocalConnectionProvider)

		val connection = provider.get // create new connection

		Future.traverse(List.fill(20)(0)) { _ =>
			Future {
				provider.get // get cached connection
			}
		}.flatMap { cs =>
			Future.traverse(cs) { c =>
				Future {
					provider.release(c) // release cached connection
				}
			}
		}

		provider.release(connection) // close connection
		// at this point connection should be closed

		(0 until 20).foreach { i =>
			println(i)
			provider.release(connection)
		}
	}
}
```

```
[info] Running rabbitmqtest.RabbitTest 
0
1
2
3
4
[error] (run-main-1) java.lang.IllegalStateException: There is no connection to release.
[error] java.lang.IllegalStateException: There is no connection to release.
[error] 	at akka.stream.alpakka.amqp.AmqpCachedConnectionProvider.release(AmqpConnectionProvider.scala:391)
[error] 	at rabbitmqtest.RabbitTest$.$anonfun$main$7(RabbitTest.scala:32)
```

**Comment by marq** [comment]
I forgot to wait for the future but I think this is still valid. I'll confirm that tomorrow.

**Comment by marq** [comment]
My bad, after fixing the test case everything looks fine. Sorry for the confusion.
