### ISSUE TITLE
[Failed] FtpsWithProxyStageTest move timeout

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#1954]
```
[error] Test akka.stream.alpakka.ftp.FtpsWithProxyStageTest.move failed: java.util.concurrent.TimeoutException: null, took 3.019 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[error]     at scala.concurrent.package$.blocking(package.scala:146)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at akka.stream.alpakka.ftp.CommonFtpStageTest.move(CommonFtpStageTest.java:128)
[error]     at akka.stream.alpakka.ftp.FtpsWithProxyStageTest.move(FtpsWithProxyStageTest.java:49)
```

https://travis-ci.com/akka/alpakka/jobs/239946344#L1535

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/260670104#L608

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/261114509#L615

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/266709836#L942 from #2006

**Comment by ennru** [comment]
Continued in #2126
