### ISSUE TITLE
[Failure] SftpWithProxyStageTest.move failed: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by seglo** [akka/alpakka#2073]
Transient failure

```
[error] Test akka.stream.alpakka.ftp.SftpWithProxyStageTest.move failed: java.util.concurrent.TimeoutException: null, took 3.008 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.scala$concurrent$java8$FuturesConvertersImpl$CF$$super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF$$anonfun$get$2.apply(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.package$.blocking(package.scala:123)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at akka.stream.alpakka.ftp.CommonFtpStageTest.move(CommonFtpStageTest.java:128)
[error]     at akka.stream.alpakka.ftp.SftpWithProxyStageTest.move(SftpWithProxyStageTest.java:49)
[error]     ...
```

https://travis-ci.com/akka/alpakka/jobs/271383951#L650

**Comment by seglo** [comment]
https://travis-ci.com/akka/alpakka/jobs/273581887#L650

**Comment by ennru** [comment]
Let's track all of these in #2126.
