### ISSUE TITLE
[Failed] FtpsWithProxyStageTest remove timeout

### ISSUE THREAD

**Issue by seglo** [akka/alpakka#2094]
```
[error] Test akka.stream.alpakka.ftp.FtpsWithProxyStageTest.remove failed: java.util.concurrent.TimeoutException: null, took 3.006 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:91)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:91)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
[error]     at scala.concurrent.package$.blocking(package.scala:124)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:91)
[error]     at akka.stream.alpakka.ftp.CommonFtpStageTest.remove(CommonFtpStageTest.java:110)
[error]     at akka.stream.alpakka.ftp.FtpsWithProxyStageTest.remove(FtpsWithProxyStageTest.java:44)
[error]     ...
```

https://travis-ci.com/akka/alpakka/jobs/275777720#L1271

Similar to #1954

**Comment by ennru** [comment]
Continued in #2126

**Comment by seglo** [comment]
It's back.

```
[error] Test akka.stream.alpakka.ftp.FtpsWithProxyStageTest.remove failed: java.util.concurrent.TimeoutException: null, took 10.047 sec
```	

https://travis-ci.com/github/akka/alpakka/jobs/324283729#L1017
