### ISSUE TITLE
UnixDomainSocketTest: aUnixDomainSocketShouldReceiveWhatIsSent

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2128]
https://travis-ci.com/akka/alpakka/jobs/283084979:
```
[error] Test docs.javadsl.UnixDomainSocketTest.aUnixDomainSocketShouldReceiveWhatIsSent failed: java.util.concurrent.TimeoutException: null, took 10.444 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
[error]     at docs.javadsl.UnixDomainSocketTest.aUnixDomainSocketShouldReceiveWhatIsSent(UnixDomainSocketTest.java:102)
[error]     ...
```

**Comment by ennru** [comment]
This is the javadsl version of #1377
