### ISSUE TITLE
JMS: Alpakka sample fails with NPE

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#2228]
### Versions used 

Akka version: 2.6.4
Alpakka JMS: 2.0.0-RC1

### Expected Behavior

https://akka.io/alpakka-samples/jms/append-to-file.html should work

### Actual Behavior

Sample `samples.javadsl.JmsToFile` fails with (`samples.scaladsl.JmsToFile` works)

```
[error] java.lang.NullPointerException
[error] 	at akka.stream.alpakka.jms.impl.JmsConnector.updateStateWith(JmsConnector.scala:112)
[error] 	at akka.stream.alpakka.jms.impl.JmsConnector.updateState(JmsConnector.scala:101)
[error] 	at akka.stream.alpakka.jms.impl.JmsConnector.updateState$(JmsConnector.scala:95)
[error] 	at akka.stream.alpakka.jms.impl.SourceStageLogic.updateState(SourceStageLogic.scala:40)
[error] 	at akka.stream.alpakka.jms.impl.SourceStageLogic.akka$stream$alpakka$jms$impl$SourceStageLogic$$stopSessions(SourceStageLogic.scala:112)
[error] 	at akka.stream.alpakka.jms.impl.SourceStageLogic$$anon$2.shutdown(SourceStageLogic.scala:139)
[error] 	at akka.stream.alpakka.jms.scaladsl.JmsConsumer$$anon$1.shutdown(JmsConsumer.scala:115)
[error] 	at akka.stream.alpakka.jms.javadsl.JmsConsumer$$anon$1.shutdown(JmsConsumer.scala:90)
[error] 	at samples.javadsl.JmsToFile.run(JmsToFile.java:78)
[error] 	at samples.javadsl.JmsToFile.main(JmsToFile.java:39)```

**Comment by ennru** [comment]
It turns out this was due to the JMS broker shutting down mids stream initialisation.
