### ISSUE TITLE
AMQP: StackOverflowError in AbstractAmqpAsyncFlowStageLogic

### ISSUE THREAD

**Issue by sturmin** [akka/alpakka#2264]
### Versions used 

Alpakka version: 2.0.0-RC1
Akka version: 2.6.4

### Expected Behavior

AMQP stage with delivery confirmation fails on connection or channel error.

### Actual Behavior

StackOverflow exception occurs

### Relevant logs

```
java.lang.StackOverflowError
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.tryFailure(Promise.scala:112)
	at scala.concurrent.Promise.tryFailure$(Promise.scala:112)
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:187)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:116)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)
	at akka.stream.alpakka.amqp.impl.AbstractAmqpAsyncFlowStageLogic.onFailure(AbstractAmqpAsyncFlowStageLogic.scala:117)

```

### Reproducible Test Case

PR with test case and fix #2263

**Comment by ennru** [comment]
Fixed with #2263
