### ISSUE TITLE
Elasticsearch: IllegalArgumentException: Cannot push to port in SimpleFlowStage

### ISSUE THREAD

**Issue by KGoodale13** [akka/alpakka#2291]
### Versions used 

Akka version: 2.5.31
Alpakka version: 2.0.0-RC2
Akka Stream Kafka version: 2.0.0
Elasticsearch version: 7.6.1
Scala version: 2.12.8

### Expected Behavior
Exceptions are not thrown in the stream

### Actual Behavior
Shortly after startup the following exception is thrown: `java.lang.IllegalArgumentException: Cannot push port (result(1791635083)) twice, or before it being pulled`

This did not happen in alpakka 1.1 which we ran previously and this only seems to happen in production (I assume due to the increased load). 

### Relevant logs

```
java.lang.IllegalArgumentException: Cannot push port (result(1791635083)) twice, or before it being pulled
	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:642)
	at akka.stream.alpakka.elasticsearch.impl.ElasticsearchSimpleFlowStage$StageLogic.handleResponse(ElasticsearchSimpleFlowStage.scala:111)
	at akka.stream.alpakka.elasticsearch.impl.ElasticsearchSimpleFlowStage$StageLogic.$anonfun$responseHandler$1(ElasticsearchSimpleFlowStage.scala:58)
	at akka.stream.alpakka.elasticsearch.impl.ElasticsearchSimpleFlowStage$StageLogic.$anonfun$responseHandler$1$adapted(ElasticsearchSimpleFlowStage.scala:58)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:452)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:481)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### Reproducible Test Case

At this time we are unable to reproduce this locally or in our development environment. I will update this issue if that changes.

**Comment by ennru** [comment]
Fixed with #2292
