### ISSUE TITLE
unable to use Slick (JDBC) with DB2

### ISSUE THREAD

**Issue by archieby** [akka/alpakka#2294]
using `akka-stream-alpakka-slick_2.13:2.0.0-RC2`
providing valid db2 jdbc driver successfully used by other applications
All the code mimics one in the example (https://doc.akka.io/docs/alpakka/current/slick.html) with a perfectly valid db query
```
final SlickSession session = SlickSession.forConfig("slick-db2");

final Object user = Slick.source(
    session,
    "SELECT COUNT(*) FROM SYSIBM.SYSDUMMY1",
    (SlickRow row) -> {
        return null;
    })
    .runWith(Sink.head(), materializer)
    .toCompletableFuture()
    .get();
```
configuration also looks exactly like in the example:
```
slick-db2 {
  profile = "slick.jdbc.DB2Profile$"
  db {
    dataSourceClass = "slick.jdbc.DriverDataSource"
    properties = {
      driver = "com.ibm.db2.jcc.DB2Driver"
      url = "jdbc:db2://XXX"
      user = "YYY"
      password = "ZZZ"
    }
  }
}
```
and that all just fails by timeout:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.sql.SQLTransientConnectionException: slick-db2.db - Connection is not available, request timed out after 30001ms.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:89)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$1(FutureConvertersImpl.scala:89)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:89)
	at com.ibm.ReaderServer.main(ReaderServer.java:67)
Caused by: java.sql.SQLTransientConnectionException: slick-db2.db - Connection is not available, request timed out after 30001ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$4.run(BasicBackend.scala:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
If I try invalid user id, I get some meaningful exception, but also wrapped in a timeout one:
```
Exception in thread "main" java.util.concurrent.ExecutionException: java.sql.SQLTransientConnectionException: slick-db2.db - Connection is not available, request timed out after 30002ms.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:89)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$1(FutureConvertersImpl.scala:89)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:89)
	at com.ibm.ReaderServer.main(ReaderServer.java:67)
Caused by: java.sql.SQLTransientConnectionException: slick-db2.db - Connection is not available, request timed out after 30002ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:250)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:249)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$4.run(BasicBackend.scala:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ibm.db2.jcc.am.SqlInvalidAuthorizationSpecException: [jcc][t4][2016][11252][3.64.106] Connection authorization failure occurred.  Reason: User ID invalid. ERRORCODE=-4214, SQLSTATE=28000
	at com.ibm.db2.jcc.am.bd.a(bd.java:677)
	at com.ibm.db2.jcc.am.bd.a(bd.java:60)
	at com.ibm.db2.jcc.am.bd.a(bd.java:120)
	at com.ibm.db2.jcc.t4.b.f(b.java:2435)
	at com.ibm.db2.jcc.t4.b.b(b.java:1804)
	at com.ibm.db2.jcc.t4.y.r(y.java:954)
	at com.ibm.db2.jcc.t4.y.k(y.java:494)
	at com.ibm.db2.jcc.t4.y.c(y.java:138)
	at com.ibm.db2.jcc.t4.b.k(b.java:1380)
	at com.ibm.db2.jcc.t4.b.b(b.java:1293)
	at com.ibm.db2.jcc.t4.b.a(b.java:6402)
	at com.ibm.db2.jcc.t4.b.b(b.java:843)
	at com.ibm.db2.jcc.t4.b.a(b.java:760)
	at com.ibm.db2.jcc.t4.b.a(b.java:421)
	at com.ibm.db2.jcc.t4.b.a(b.java:396)
	at com.ibm.db2.jcc.t4.b.<init>(b.java:334)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:232)
	at com.ibm.db2.jcc.DB2SimpleDataSource.getConnection(DB2SimpleDataSource.java:198)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:475)
	at com.ibm.db2.jcc.DB2Driver.connect(DB2Driver.java:116)
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by archieby** [comment]
Configuration like this works:
```
slick-db2 {
  profile = "slick.jdbc.DB2Profile$",
  db {
    driver = "com.ibm.db2.jcc.DB2Driver"
    url = "xxx"
    user = "xxx"
    password = "xxx"
    connectionPool = disabled
  }
}
```
but is there any way to use slick with a connection pool?

**Comment by archieby** [comment]
it looks like setting `connectionTestQuery` resolved the issue:
```
slick-db2 {
  profile = "slick.jdbc.DB2Profile$"
  db {
    dataSourceClass = "slick.jdbc.DriverDataSource"
    connectionTestQuery = "SELECT 1 FROM SYSIBM.SYSDUMMY1"
    properties = {
      driver = "com.ibm.db2.jcc.DB2Driver"
      url = "xxx"
      user = "xxx"
      password = "xxx"
    }
  }
}
```
but it would be nice to have that mentioned some place in the documentation.
Getting some meaningful exception would also help

**Comment by ennru** [comment]
Thank you for posting your solution to this. Feel free to suggest an update to the Alpakka documentation in a Pull Request.

**Comment by ramakrishna-hande** [comment]
Hi I have a similar issue for MySQL.
My query does  not get executed at all.

It keeps waiting forever. I dont get any error also. Please help
