### ISSUE TITLE
Failed: AwsLambdaFlowSpec

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#235]
Failed while validating #233

https://travis-ci.org/akka/alpakka/jobs/215442139

```
[info] AwsLambdaFlow
[info] - should call a single invoke request *** FAILED *** (226 milliseconds)
[info]   org.mockito.exceptions.verification.TooLittleActualInvocations: aWSLambdaAsyncClient.invokeAsync(
[info]     {FunctionName: test_function,Payload: java.nio.HeapByteBuffer[pos=0 lim=12 cap=12],},
[info]     <any>
[info] );
[info] Wanted 1 time:
[info] -> at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AwsLambdaFlowSpec.scala:69)
[info] But was 0 times.
[info]   at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AwsLambdaFlowSpec.scala:69)
[info]   at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AwsLambdaFlowSpec.scala:54)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec.withFixture(AwsLambdaFlowSpec.scala:24)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(AwsLambdaFlowSpec.scala:24)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
[info]   at akka.stream.alpakka.awslambda.scaladsl.AwsLambdaFlowSpec.runTest(AwsLambdaFlowSpec.scala:24)
...
```

**Comment by 2m** [comment]
Failed again when validating PR: https://travis-ci.org/akka/alpakka/jobs/215475134

**Comment by raboof** [comment]
Could #261 help here? Not completely sure as I haven't been able to reproduce exactly this failure, but seems plausible to me.

**Comment by 2m** [comment]
I think you are right. Failure mentioned here was that some mockito expectation was not fulfilled.
