### ISSUE TITLE
Failed: FtpsStageSpec

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#236]
While building master: https://travis-ci.org/akka/alpakka/jobs/215458574

```
[info] - should retrieve relevant file attributes *** FAILED *** (650 milliseconds)
[info]   60606 milliseconds was not less than 1 minute,
[info]   inside FtpFile(sample,/sample,false,801,1490607120000,Set(OWNER_READ, OWNER_WRITE)) (CommonFtpStageSpec.scala:73)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$$nestedInanonfun$$init$$5$1.applyOrElse(CommonFtpStageSpec.scala:73)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$$nestedInanonfun$$init$$5$1.applyOrElse(CommonFtpStageSpec.scala:67)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
[info]   at org.scalatest.Inside.inside(Inside.scala:128)
[info]   at org.scalatest.Inside.inside$(Inside.scala:103)
[info]   at akka.stream.alpakka.ftp.FtpsStageSpec.inside(CommonFtpStageSpec.scala:17)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec.$anonfun$$init$$5(CommonFtpStageSpec.scala:67)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.stream.alpakka.ftp.FtpsStageSpec.withFixture(CommonFtpStageSpec.scala:17)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[info]   at akka.stream.alpakka.ftp.FtpsStageSpec.org$scalatest$BeforeAndAfter$$super$runTest(CommonFtpStageSpec.scala:17)
[info]   at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
[info]   at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
[info]   at akka.stream.alpakka.ftp.FtpsStageSpec.runTest(CommonFtpStageSpec.scala:17)
...
```

**Comment by filosganga** [comment]
That test seems flaky, it has failed couple of time yesterday on my PR as well.
