### ISSUE TITLE
DelaySpec: should work as passthrough if should delay returns false

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2361]
and others

https://travis-ci.com/github/akka/alpakka/jobs/364151701

```
info] Delay

[info] - should work as passthrough if should delay returns false *** FAILED *** (35 milliseconds)

[info]   java.lang.AssertionError: expected OnNext, found OnComplete

[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:370)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.$anonfun$new$6(DelaySpec.scala:42)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.$anonfun$new$6$adapted(DelaySpec.scala:39)

[info]   at scala.collection.immutable.Range.foreach(Range.scala:158)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.$anonfun$new$2(DelaySpec.scala:39)

[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)

[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)

[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)

[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)

[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)

[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)

[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.withFixture(DelaySpec.scala:19)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1074)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1086)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1068)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.runTest(DelaySpec.scala:19)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)

[info]   at scala.collection.immutable.List.foreach(List.scala:392)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)

[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)

[info]   at scala.collection.immutable.List.foreach(List.scala:392)

[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)

[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)

[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1145)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1144)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.runTests(DelaySpec.scala:19)

[info]   at org.scalatest.Suite.run(Suite.scala:1112)

[info]   at org.scalatest.Suite.run$(Suite.scala:1094)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(DelaySpec.scala:19)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:535)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1190)

[info]   at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1188)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.org$scalatest$BeforeAndAfterAll$$super$run(DelaySpec.scala:19)

[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)

[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)

[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)

[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.DelaySpec.run(DelaySpec.scala:19)

[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)

[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)

[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)

[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ennru** [comment]
https://travis-ci.com/github/akka/alpakka/jobs/369284591#L541

**Comment by ennru** [comment]
Both logged failures are in the scheduled build using Akka 2.6, I wonder if there could be something to it.

**Comment by raboof** [comment]
https://travis-ci.com/github/akka/alpakka/jobs/372391240

**Comment by raboof** [comment]
Indeed seems broken on 2.6.

Delay is built on top of Splitter, so I suspect this is a symptom of #2378. Closing for now, let's reopen when it appears again after #2378 is fixed

**Comment by raboof** [comment]
Seems separate after all

**Comment by raboof** [comment]
What happens here is that when the input is completed, the 'delayed' side of the split and the 'non-delayed' side of the split are both completed, and whichever completes first will complete the output.

This means that when there are no delayed elements, and the input completes, this completion may overtake elements still on the 'non-delaying' side, as is visible in test failures.

One solution might be to set `eagerComplete` to 'false'. This will mean that when the input completes, the stage will wait for both branches to complete before completing itself. It's not completely obvious if that's desirable: do we want to wait for delayed elements in this case? If not, perhaps we should adapt the DelayFlow stage accordingly.

@tg44 what do you think?

**Comment by tg44** [comment]
I'm not sure. I think this happens because of the splitter implementation modified.

The splitter is a broadcast with two filters. Before the filter pre-pull the merge get the closed message when the last element went through the `bc->f->d->m` or the `bc->f->m` path, then the bc get pulled from both upstreams, get the close message and propagated it. Now after the filter pre-pull, the `bc->f->d` can hold the elemet while both filters pull the bc, which gets the close, and propagate it to the `bc->f->m` path closing the merge, causing a lost element.

Two fix can be done, one is what you propose, removing the eagerComplete. The other is to force the Splitter to work as we wanted it to work at the first time. I think we should reimplemet/fix the splitter, and check if this issue still appears or not (my bet is the not). Also, I think not consciously fixing this issue will break something big time. This connector has a cycle in it, which made it really fragile, and really dependant on the current stages backpressure capabilities, so the test was written to spot these errors. Simply bypassing them will introduce deadlocks or random element drops for sure.

**Comment by raboof** [comment]
(thanks! for future reference: see also #2379 :) )
