### ISSUE TITLE
UnixDomainSocketSpec: A Unix Domain Socket should not be able to connect to a non-existent file

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2437]
https://travis-ci.com/github/akka/alpakka/jobs/395191967
```
[info]   The future returned an exception of type: scala.concurrent.Future$$anon$3, with message: Future.failed not completed with a throwable.. (UnixDomainSocketSpec.scala:180)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at docs.scaladsl.UnixDomainSocketSpec.$anonfun$new$20(UnixDomainSocketSpec.scala:180)
```

**Comment by ennru** [comment]
Duplicate of #1649

**Comment by raboof** [comment]
ah, seems the stack trace changed since but might be the same issue indeed.
