### ISSUE TITLE
PravegaGraphSpec: Pravega connector should runs sources

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#2453]
https://travis-ci.com/github/akka/alpakka/jobs/403083496

```
[info] PravegaGraphSpec:
[info] Pravega connector
[info] - should runs sources *** FAILED *** (10 seconds, 294 milliseconds)
[info]   java.util.concurrent.TimeoutException: Futures timed out after [10 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:187)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:195)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
[info]   at scala.concurrent.Await$.ready(package.scala:146)
[info]   at akka.stream.alpakka.pravega.PravegaGraphSpec.$anonfun$new$2(PravegaGraphSpec.scala:65)
```

**Comment by ennru** [comment]
This seems to fail very often.
https://travis-ci.com/github/akka/alpakka/jobs/408586344#L390 in #2508

**Comment by cheleb** [comment]
Is this issue still open ?

**Comment by seglo** [comment]
This issue hasn't been observed (at least, it hasn't been logged here) since the PR, so I think it's safe to close. We can reopen it if necessary.
