### ISSUE TITLE
Erratic "PERMISSION_DENIED: The request is missing a valid API key" - when using Alpakka PubSub GRPC connector

### ISSUE THREAD

**Issue by marcinaylien** [akka/alpakka#2735]
### Versions used 

Akka version: 2.6.16
Alpakka version: 3.0.3
JDK version: OpenJDK 11.0.11
Scala version: 2.13.6

### Expected Behavior
Application runs on Kubernetes in GCP using default authentication (service account) and default configuration of the connector (we change/override nothing)
When application starts it connects to PubSub and Akka Stream should start processing the messages. It does so in 99% of cases but...

### Actual Behavior
Sporadically app fails with `PERMISSION_DENIED: The request is missing a valid API key` when starting the stream. Restarting stream does not help - it can be only fixed by restart of the pod.

### Relevant logs
```
io.grpc.StatusRuntimeException: PERMISSION_DENIED: The request is missing a valid API key.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at akka.grpc.internal.UnaryCallAdapter.onClose(UnaryCallAdapter.scala:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Reproducible Test Case
The issue is not reproducible with test.

**Comment by gurpreet-singh-exa** [comment]
@ennru @marcinaylien  is it fixed in any version?

**Comment by marcinaylien** [comment]
So, the issue is caused by a call to Google's Compute Engine that times out. Because of that Alpakka fails to obtain API key. There's no retry. And then, each call to PubSub fails with PERMISSION_DENIED due to a missing API key. 

I am mitigating the issue by increasing a default timeout `compute-engine.timeout` to a much higher value. The reason why the call timeouts is unrelated to Alpakka - it is Google's fault. Still, it is not great that even though authentication fails Alpakka does not err and it required quite a digging to find out the root cause.
