### ISSUE TITLE
GCS - Object is missing required member 'access_token'

### ISSUE THREAD

**Issue by pbagriy** [akka/alpakka#2736]
Upload to GCS fails with exception. Seems like the same issue as #2080 . Version 2.0.2 works correctly, but all versions starting with 3.0.0+ have this issue again 

### Versions used 
Alpakka version: 3.0.3

### Relevant logs
```
spray.json.DeserializationException: Object is missing required member 'access_token'
at spray.json.package$.deserializationError(package.scala:23)
at spray.json.ProductFormats.fromField(ProductFormats.scala:61)
at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:81)
at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:71)
at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:31)
at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:22)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:50)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: key not found: access_token
at scala.collection.MapOps.default(Map.scala:251)
at scala.collection.MapOps.default$(Map.scala:250)
at scala.collection.AbstractMap.default(Map.scala:381)
at scala.collection.MapOps.apply(Map.scala:153)
at scala.collection.MapOps.apply$(Map.scala:152)
at scala.collection.AbstractMap.apply(Map.scala:381)
at spray.json.ProductFormats.fromField(ProductFormats.scala:58)
... 21 common frames omitted
```

**Comment by pbagriy** [comment]
After a bit more research I found that problem was with credentials. Old credentials config format is marked as deprecated in reference.conf and there is warning in the logs when `alpakka.google.cloud.storage` block is present in application.conf. After changing it to new format it started working as expected.

What I didn't expect is that old config would break my program completely. Config that I used: 
```
alpakka {
  google {
    //current
    credentials {
      service-account {
        project-id = ${?GCS_PROJECT_ID}
        client-email = ${?GCS_CLIENT_EMAIL}
        private-key = ${?GCS_PRIVATE_KEY}
      }
    }

    //deprecated
    cloud.storage {
      private-key = ${?GCS_PRIVATE_KEY}
      project-id = ${?GCS_PROJECT_ID}
      client-email = ${?GCS_CLIENT_EMAIL}
    }
  }
```
Code works fine only when upper block(marked current) is included.

In the end it looks like https://github.com/akka/alpakka/pull/2164 needs a follow-up, because error message was not helpful at all. And warning for deprecated config should probably be replaced with error if it's really the reason for error and not some other mistake on my part.

**Comment by ennru** [comment]
Thank you for adding your findings here. It is always hard to weigh deprecation warnings and failing it altogether.
Would you be in a position to suggest a more helpful handling via a PR?
