### ISSUE TITLE
GCS call to GCStorage.rewrite(..).withAttributes(GoogleAttributes.settings(myCustomSettings)) does not take into account customsettings

### ISSUE THREAD

**Issue by ramazanyich** [akka/alpakka#2753]
Alpakka version: 3.0.3

We are using custom settings to provide google configuration settings like projectId, privatekey, etc. to CGSStorage API calls.
we make use of withAttributes() api call to different GCStorage API calls: GCStorage.deleteObject, listObject,simpleUpload, etc.
it works for all of them excerpt call to GCStorage.rewrite(..).withAttributes(GoogleAttributes.settings(myCustomSettings)) 
We get a 401 error. This is the code which we use. The   withAttributes(GoogleAttributes.settings(customSettings)) code is used for all our other GCStorage calls and it is the same.
```
  GCStorage
          .rewrite(
            googleStorageConfiguration.bucket,
            getFileName(oldObject.id),
            googleStorageConfiguration.bucket,
            getFileName(newObject.id)
          )
          .withAttributes(GoogleAttributes.settings(customSettings))
```
with alpakka version 2.0.2 it did work.
this is old code which did work:
```
 GCStorage
          .rewrite(
            googleStorageConfiguration.bucket,
            getFileName(oldObject.id),
            googleStorageConfiguration.bucket,
            getFileName(newObject.id)
          )
          .withAttributes(GCStorageAttributes.settings(customSettings))
```

stacktrace
```
[401] {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}}
java.lang.RuntimeException: [401] {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}}
	at akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$optionUnmarshaller$5(GCStorageStream.scala:258)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:256)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:36)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:36)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:85)
	at scala.concurrent.Future.flatMap(Future.scala:254)
	at scala.concurrent.Future.flatMap$(Future.scala:254)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:76)
	at akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$optionUnmarshaller$3(GCStorageStream.scala:257)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.stream.alpakka.google.implicits$FromResponseUnmarshallerRetryHelpers$.$anonfun$withDefaultRetry$3(implicits.scala:29)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at akka.stream.alpakka.google.http.GoogleHttp$.$anonfun$singleRequest$1(GoogleHttp.scala:60)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:393)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:242)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at akka.http.impl.engine.client.PoolInterface$Logic.onPush(PoolInterface.scala:146)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by ennru** [comment]
Fixed with #2794
