### ISSUE TITLE
Failed: MqttSourceSpec should support will message

### ISSUE THREAD

**Issue by 2m** [akka/alpakka#290]
While validating https://github.com/akka/alpakka/pull/289

https://travis-ci.org/akka/alpakka/jobs/229954352

```
[info] - should support will message *** FAILED *** (251 milliseconds)
[info]   The future returned an exception of type: org.eclipse.paho.client.mqttv3.MqttException, with message: Unable to connect to server. (MqttSourceSpec.scala:198)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:523)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:676)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec.whenReady(MqttSourceSpec.scala:21)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$11.apply(MqttSourceSpec.scala:198)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$10$$anonfun$apply$11.apply(MqttSourceSpec.scala:187)
[info]   at org.scalatest.concurrent.Futures$class.whenReady(Futures.scala:677)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec.whenReady(MqttSourceSpec.scala:21)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(MqttSourceSpec.scala:187)
[info]   at akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$10.apply(MqttSourceSpec.scala:178)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
...
```

**Comment by 2m** [comment]
This one started to fail almost constantly now:
https://travis-ci.org/akka/alpakka/jobs/241206709

**Comment by raboof** [comment]
This still seems to happen a lot, also for https://travis-ci.org/akka/alpakka/builds/250323255

**Comment by raboof** [comment]
https://travis-ci.org/akka/alpakka/jobs/253955264

**Comment by raboof** [comment]
Hm, these tests seem to succeed reliably for me locally, and this is not the first test, so it doesn't appear to be an initialization issue.

Perhaps the next step would be making sure travis dumps the `mqtt` docker container logs after a test failure, so we can see if there's anything interesting in there?

**Comment by raboof** [comment]
OK nothing obviously wrong here.. https://travis-ci.org/akka/alpakka/jobs/254460747

```
mqtt_1       | 1500301532: mosquitto version 1.4.12 (build date Thu, 25 May 2017 22:38:16 +0100) starting
mqtt_1       | 1500301532: Config loaded from /mqtt/config/mosquitto.conf.
mqtt_1       | 1500301532: Opening ipv4 listen socket on port 1883.
mqtt_1       | 1500301532: Opening ipv6 listen socket on port 1883.
mqtt_1       | 1500301897: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301897: New client connected from 172.18.0.1 as source-test/source (c1, k60).
mqtt_1       | 1500301897: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301897: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301897: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301897: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301897: New client connected from 172.18.0.1 as source-test/sink (c1, k60).
mqtt_1       | 1500301897: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: Client source-test/sink disconnected.
mqtt_1       | 1500301898: Client source-test/source disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Client source-spec/source already connected, closing old connection.
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as sink-spec/source (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as sink-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client sink-spec/sink disconnected.
mqtt_1       | 1500301898: Client sink-spec/source disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Socket error on client <unknown>, disconnecting.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Socket error on client <unknown>, disconnecting.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as sink-spec/source (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/source (c1, k60, u'username1').
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as sink-spec/sink (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/sink (c1, k60, u'username1').
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Client source-spec/source already connected, closing old connection.
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301898: Client sink-spec/sink disconnected.
mqtt_1       | 1500301898: Client sink-spec/source disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Socket error on client <unknown>, disconnecting.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Socket error on client <unknown>, disconnecting.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Client source-spec/source already connected, closing old connection.
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as sink-spec/sink (c1, k60, u'username1').
mqtt_1       | 1500301898: Client sink-spec/sink disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: Client source-spec/source already connected, closing old connection.
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301898: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301898: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301898: Client source-spec/sink disconnected.
mqtt_1       | 1500301898: Client source-spec/source disconnected.
mqtt_1       | 1500301899: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301899: New client connected from 172.18.0.1 as source-spec/source (c1, k60).
mqtt_1       | 1500301899: New connection from 172.18.0.1 on port 1883.
mqtt_1       | 1500301899: New client connected from 172.18.0.1 as source-spec/sink (c1, k60).
mqtt_1       | 1500301899: Client source-spec/sink disconnected.
mqtt_1       | 1500301899: Client source-spec/source disconnected.
```

**Comment by raboof** [comment]
and https://travis-ci.org/akka/alpakka/jobs/254777956

**Comment by raboof** [comment]
It seems the failing builds have:
```
[INFO] [07/18/2017 14:02:09.913] [MqttSinkSpec-akka.actor.default-dispatcher-3] [akka://MqttSinkSpec/system/IO-TCP/selectors/$a/1] Message [akka.io.Tcp$Register] from Actor[akka://MqttSinkSpec/user/StreamSupervisor-2/$$c#1575068261] to Actor[akka://MqttSinkSpec/system/IO-TCP/selectors/$a/1#1709804863] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] - should stores animals in geode (309 milliseconds)
[INFO] [07/18/2017 14:02:09.998] [MqttSinkSpec-akka.actor.default-dispatcher-3] [akka://MqttSinkSpec/system/IO-TCP/selectors/$a/2] Message [akka.io.Dns$Resolved] from Actor[akka://MqttSinkSpec/system/IO-DNS/inet-address/$b#-753235759] to Actor[akka://MqttSinkSpec/system/IO-TCP/selectors/$a/2#-26779091] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```
while the succeeding ones don't, but it's unclear wether that's a cause or an effect.

**Comment by raboof** [comment]
This is still a problem (https://travis-ci.org/akka/alpakka/jobs/276827603)

**Comment by raboof** [comment]
https://travis-ci.org/akka/alpakka/jobs/301342389

**Comment by raboof** [comment]
(Even though we put the flakey test on 'ignore', it would still be good to get to the bottom of what's going on with this test, so leaving open)
