### ISSUE TITLE
AWS S3 Invalid continuation token.

### ISSUE THREAD

**Issue by fydio** [akka/alpakka#330]
On a bucket with over 1000 files in it, getting a listing with `S3Client.listBucket` throws the following exception:

```
akka.stream.alpakka.s3.S3Exception: The continuation token provided is incorrect
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$entityForSuccess$1(S3Stream.scala:256)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Scalahansolo** [comment]
I implemented that method. Ill take a look.

**Comment by Scalahansolo** [comment]
Can you post an example of what your continuation token is, as well as what you expect it to be to help debugging?

**Comment by vlovgr** [comment]
The problem seems to be the `replaceAll` here: 

https://github.com/akka/alpakka/blob/master/s3/src/main/scala/akka/stream/alpakka/s3/impl/HttpRequests.scala#L29

Removing the `replaceAll`, everything works fine for me. The `withQuery` method should take care of all escaping like this, so should be no need to do it manually.

**Comment by Scalahansolo** [comment]
Ahh I see. I can open a RB for this, or would you rather open that?

**Comment by vlovgr** [comment]
@Scalahansolo Please go ahead and open a PR. 👍

**Comment by Scalahansolo** [comment]
Done
