### ISSUE TITLE
Failed: CommonFtpStageSpec

### ISSUE THREAD

**Issue by francisdb** [akka/alpakka#361]
Flakey ftp tests, see also #236 

I have seen other ftp tests fail with the same: `java.security.SignatureException: Invalid encoding for signature`

```
[info] FtpBrowserSource
[info] - should list all files from root *** FAILED *** (406 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected class akka.stream.testkit.TestSubscriber$OnNext, found class akka.stream.testkit.TestSubscriber$OnError (OnError(com.jcraft.jsch.JSchException: Session.connect: java.security.SignatureException: Invalid encoding for signature
[info] 	at com.jcraft.jsch.Session.connect(Session.java:565)
[info] 	at com.jcraft.jsch.Session.connect(Session.java:183)
[info] 	at akka.stream.alpakka.ftp.impl.SftpOperations.$anonfun$connect$1(SftpOperations.scala:43)
[info] 	at scala.util.Try$.apply(Try.scala:209)
[info] 	at akka.stream.alpakka.ftp.impl.SftpOperations.connect(SftpOperations.scala:30)
[info] 	at akka.stream.alpakka.ftp.impl.SftpOperations.connect$(SftpOperations.scala:30)
[info] 	at akka.stream.alpakka.ftp.impl.FtpLike$$anon$2.connect(FtpLike.scala:34)
[info] 	at akka.stream.alpakka.ftp.impl.FtpLike$$anon$2.connect(FtpLike.scala:34)
[info] 	at akka.stream.alpakka.ftp.impl.FtpGraphStageLogic.preStart(FtpGraphStageLogic.scala:26)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:290)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707)
[info] 	at akka.actor.Actor.aroundPreStart(Actor.scala:521)
[info] 	at akka.actor.Actor.aroundPreStart$(Actor.scala:521)
[info] 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:583)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:454)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:476)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info] 	at java.lang.Thread.run(Thread.java:748)
[info] ))
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:487)
[info]   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:459)
[info]   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:459)
[info]   at akka.testkit.TestKit.expectMsgType(TestKit.scala:828)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:339)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec.$anonfun$$init$$2(CommonFtpStageSpec.scala:74)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.withFixture(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.org$scalatest$BeforeAndAfter$$super$runTest(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.BeforeAndAfter.runTest(BeforeAndAfter.scala:203)
[info]   at org.scalatest.BeforeAndAfter.runTest$(BeforeAndAfter.scala:192)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.runTest(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.runTests(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.org$scalatest$WordSpecLike$$super$run(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.org$scalatest$BeforeAndAfter$$super$run(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.BeforeAndAfter.run(BeforeAndAfter.scala:258)
[info]   at org.scalatest.BeforeAndAfter.run$(BeforeAndAfter.scala:256)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.org$scalatest$BeforeAndAfterAll$$super$run(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.stream.alpakka.ftp.SftpStageSpec.run(CommonFtpStageSpec.scala:21)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
```

and 

https://travis-ci.org/akka/alpakka/jobs/247406685

```
FtpBrowserSource & FtpIOSource
[info] - should work together retrieving a list of files *** FAILED *** (5 seconds, 71 milliseconds)
[info]   15219 was not equal to 16020 (CommonFtpStageSpec.scala:159)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$3$$anonfun$apply$mcV$sp$10.apply(CommonFtpStageSpec.scala:159)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$3$$anonfun$apply$mcV$sp$10.apply(CommonFtpStageSpec.scala:146)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.withFixture(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfter$$super$runTest(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.runTest(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.runTests(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$WordSpecLike$$super$run(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfter$$super$run(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfterAll$$super$run(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.run(CommonFtpStageSpec.scala:38)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:237)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by juanjovazquez** [comment]
Apparently, it seems to have to do with [this regression](https://sourceforge.net/p/jsch/bugs/111/).

**Comment by francisdb** [comment]
Should we disable those tests until this is fixed upstream?

**Comment by raboof** [comment]
@juanjovazquez good find! Travis is running at oracle jdk 1.8.0_131, so that sounds plausible. If that's the issue then that points to something that would break in production as well, not just a test failure. I'll create an issue for that, and it seems reasonable to ignore this test until we pick up that issue.

**Comment by juanjovazquez** [comment]
@raboof yeah, it sounds reasonable to ignore these tests for the time being. OTOH, depending on the response we get from the Jsch side regarding this issue, maybe we'd have to face a replacement for this library.

**Comment by francisdb** [comment]
I guess we can close this one and the pull request for #365 should re-enable the tests?
