### ISSUE TITLE
whitesource build failure

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#371]
An build showed an intermittent failure with the following error:
```
[error] Error communicating with service: Illegal arguments: Organization token is missing
sbtwhitesource.WhiteSourceException: Error communicating with service: Illegal arguments: Organization token is missing
	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:314)
	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:296)
	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:67)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:151)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:147)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.whitesource.agent.client.WssServiceException: Illegal arguments: Organization token is missing
	at org.whitesource.agent.client.WssServiceClientImpl.extractResultData(WssServiceClientImpl.java:322)
	at org.whitesource.agent.client.WssServiceClientImpl.service(WssServiceClientImpl.java:220)
	at org.whitesource.agent.client.WssServiceClientImpl.checkPolicyCompliance(WssServiceClientImpl.java:151)
	at org.whitesource.agent.client.WhitesourceService.checkPolicyCompliance(WhitesourceService.java:164)
	at sbtwhitesource.CheckPoliciesAction.sendCheckPolicies(WhiteSource.scala:303)
	at sbtwhitesource.CheckPoliciesAction.doExecute(WhiteSource.scala:296)
	at sbtwhitesource.BaseAction.execute(WhiteSource.scala:67)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:151)
	at sbtwhitesource.WhiteSourcePlugin$$anonfun$projectSettings$3.apply(WhiteSourcePlugin.scala:147)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`
```

**Comment by raboof** [comment]
Another one: https://travis-ci.org/akka/alpakka/jobs/250806531

**Comment by mpricope** [comment]
looks like mine suffers from the same symptom: https://travis-ci.org/akka/alpakka/jobs/270540454

**Comment by raboof** [comment]
Recently understood what's going on there: travis doesn't make secrets available when building PR's from non-project-members, so it can't authenticate to whitesource. I'll disable it for PR's.
