### ISSUE TITLE
S/FTP sink materializes a successful IOResult if connection fails during upload  

### ISSUE THREAD

**Issue by frj** [akka/alpakka#380]
Hi there,

We are having an issue with the Sftp sink. It is reporting a successful upload in the event of an IOException happening during the upload its self.

Heres the test app Im using 

```scala
import java.net.InetAddress

import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.alpakka.ftp.FtpCredentials.NonAnonFtpCredentials
import akka.stream.alpakka.ftp.SftpSettings
import akka.stream.alpakka.ftp.scaladsl.Sftp
import akka.stream.scaladsl.{Keep, Source}
import akka.util.ByteString

object TestFtpSink extends App {
  private val host = InetAddress.getByName(args(0))
  private val path = args(1)
  private val username = args(2)
  private val password = args(3)

  implicit val actorSystem = ActorSystem("test")
  implicit val materializer = ActorMaterializer()
  implicit val ec = actorSystem.dispatcher

  val settings = SftpSettings(host = host,
                              credentials = NonAnonFtpCredentials(username, password),
                              strictHostKeyChecking = false)

  private val future = Source.repeat(ByteString(0x00)).toMat(Sftp.toPath(path, settings))(Keep.right).run()

  future.onComplete { result ⇒
    println(result)
    actorSystem.terminate()
  }
}
```
```scala
lazy val root = (project in file("."))
  .settings(
    name := "graph-stage-test",
    scalaVersion := "2.12.2",
    libraryDependencies += "com.lightbend.akka" %% "akka-stream-alpakka-ftp" % "0.10"
  )
```
The steps Im using to reproduce are:
* I run the above app against the sftp sever
* Wait until the file has been created remotely
* Kill the network on the local machine 
* wait a few seconds

The output I see is as follows:

```
[ERROR] [07/05/2017 11:15:05.281] [test-akka.stream.default-blocking-io-dispatcher-11] [akka://test/user/StreamSupervisor-0/flow-0-1-sFtpIOSink] Error in stage [akka.stream.alpakka.ftp.impl.FtpSourceFactory$$anon$3@16e96c32]: Broken pipe (Write failed)
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at com.jcraft.jsch.IO.put(IO.java:60)
	at com.jcraft.jsch.Session._write(Session.java:1379)
	at com.jcraft.jsch.Session.write(Session.java:1343)
	at com.jcraft.jsch.ChannelSftp.sendWRITE(ChannelSftp.java:2646)
	at com.jcraft.jsch.ChannelSftp.access$100(ChannelSftp.java:36)
	at com.jcraft.jsch.ChannelSftp$1.write(ChannelSftp.java:806)
	at com.jcraft.jsch.ChannelSftp$1.write(ChannelSftp.java:789)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$write$1(FtpIOGraphStage.scala:182)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$write$1$adapted(FtpIOGraphStage.scala:181)
	at scala.Option.foreach(Option.scala:257)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.akka$stream$alpakka$ftp$impl$FtpIOSinkStage$$anon$$write(FtpIOGraphStage.scala:181)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2$$anon$4.onPush(FtpIOGraphStage.scala:141)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[ERROR] [07/05/2017 11:15:05.287] [test-akka.stream.default-blocking-io-dispatcher-11] [akka://test/user/StreamSupervisor-0/flow-0-1-sFtpIOSink] Error during postStop in [akka.stream.alpakka.ftp.impl.FtpSourceFactory$$anon$3@16e96c32]: inputstream is closed
java.io.IOException: inputstream is closed
	at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2911)
	at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2935)
	at com.jcraft.jsch.ChannelSftp.checkStatus(ChannelSftp.java:2473)
	at com.jcraft.jsch.ChannelSftp.access$300(ChannelSftp.java:36)
	at com.jcraft.jsch.ChannelSftp$1.flush(ChannelSftp.java:851)
	at com.jcraft.jsch.ChannelSftp$1.close(ChannelSftp.java:867)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$postStop$2(FtpIOGraphStage.scala:163)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$postStop$2$adapted(FtpIOGraphStage.scala:163)
	at scala.Option.foreach(Option.scala:257)
	at akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.postStop(FtpIOGraphStage.scala:163)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:801)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:780)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:620)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor.aroundReceive(Actor.scala:502)
	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Success(IOResult(71198,Success(Done)))

Process finished with exit code 0
```

This seems incorrect, I would expect the IOResult materialized by the stream to contain a Failure wrapping the original SocketException

**Comment by juanjovazquez** [comment]
@raboof This should be labelled as `p:ftp` right?
