### ISSUE TITLE
KeyfileSftpSourceSpec should fail and report the exception in the result status if connection fails

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#410]
Suspected by @juanjovazquez to be related to #386

```
- should fail and report the exception in the result status if connection fails *** FAILED *** (10 seconds, 831 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 35 times, sleeping 300 milliseconds between each query. (CommonFtpStageSpec.scala:261)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$5$$anonfun$apply$mcV$sp$16.apply(CommonFtpStageSpec.scala:261)
[info]   at akka.stream.alpakka.ftp.CommonFtpStageSpec$$anonfun$5$$anonfun$apply$mcV$sp$16.apply(CommonFtpStageSpec.scala:248)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.withFixture(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfter$$super$runTest(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:203)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.runTest(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.runTests(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$WordSpecLike$$super$run(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfter$$super$run(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.org$scalatest$BeforeAndAfterAll$$super$run(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.stream.alpakka.ftp.KeyFileSftpSourceSpec.run(CommonFtpStageSpec.scala:43)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:296)
[info]   at sbt.ForkMain$Run$2.call(ForkMain.java:286)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by raboof** [comment]
Also happened as `akka.stream.alpakka.ftp.RawKeySftpSourceSpec` in https://travis-ci.org/akka/alpakka/jobs/253955266

**Comment by raboof** [comment]
And `StrictHostCheckingSftpSourceSpec` https://travis-ci.org/akka/alpakka/jobs/254405398

**Comment by raboof** [comment]
Hmm, the failure in https://travis-ci.org/akka/alpakka/jobs/256038302 suggests the `write` is still blocking?
```
default-akka.stream.default-blocking-io-dispatcher-10
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
 net.schmizz.concurrent.Promise.tryRetrieve(Promise.java:171)
 net.schmizz.concurrent.Promise.retrieve(Promise.java:138)
 net.schmizz.sshj.sftp.RemoteFile.checkWriteResponse(RemoteFile.java:92)
 net.schmizz.sshj.sftp.RemoteFile.access$000(RemoteFile.java:30)
 net.schmizz.sshj.sftp.RemoteFile$RemoteFileOutputStream.write(RemoteFile.java:143)
 java.io.OutputStream.write(OutputStream.java:75)
 akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$write$1(FtpIOGraphStage.scala:193)
 akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.$anonfun$write$1$adapted(FtpIOGraphStage.scala:192)
 akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2$$Lambda$475/1632339005.apply(Unknown Source)
 scala.Option.foreach(Option.scala:257)
 akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2.akka$stream$alpakka$ftp$impl$FtpIOSinkStage$$anon$$write(FtpIOGraphStage.scala:192)
 akka.stream.alpakka.ftp.impl.FtpIOSinkStage$$anon$2$$anon$4.onPush(FtpIOGraphStage.scala:143)
 akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
 akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:710)
 akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
 akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
 akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:410)
 akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
 akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
 akka.actor.Actor.aroundReceive(Actor.scala:502)
 akka.actor.Actor.aroundReceive$(Actor.scala:500)
 akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
 akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
 akka.actor.ActorCell.invoke(ActorCell.scala:495)
 akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
 akka.dispatch.Mailbox.run(Mailbox.scala:224)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:748)
```

**Comment by ennru** [comment]
We haven't seen this for a while AFAIK.
