### ISSUE TITLE
S3 - upload error (Unsupported Content-Type, supported: application/octet-stream)

### ISSUE THREAD

**Issue by Porcupine96** [akka/alpakka#457]
I'm getting the following error when trying to upload a file to S3:

```
[ERROR] [09/04/2017 00:08:51.372] [UploadServiceActorSystem-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(UploadServiceActorSystem)] Error during processing of request: 'HttpRequest(HttpMethod(POST),http://127.0.0.1:5000/,List(Cache-Control: no-cache, Postman-Token: e5f0ed0c-32ba-4352-946c-9666e1a625c0, User-Agent: PostmanRuntime/3.0.11-hotfix.2, Accept: */*, Host: 127.0.0.1:5000, Accept-Encoding: gzip, deflate, Connection: keep-alive, Timeout-Access: <function1>),HttpEntity.Default(multipart/form-data; boundary=--------------------------457199731057959524831986,179557 bytes total),HttpProtocol(HTTP/1.1))'.
akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/octet-stream
	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:158)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$.$anonfun$forContentTypes$3(Unmarshaller.scala:114)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$.$anonfun$mapWithInput$3(Unmarshaller.scala:91)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$initiateMultipartUpload$3(S3Stream.scala:130)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

In `package akka.stream.alpakka.s3.impl.S3Stream` method `initiateMultipartUpload` the initialization response has content type `application/xml` and because of that
```
case HttpResponse(status, _, entity, _) if status.isSuccess() =>
        Unmarshal(entity).to[MultipartUpload]
``` 
fails.

Have anyone had similiar issure?

I'm using scala 2.12.3 and alpakka 0.11.

**Comment by Porcupine96** [comment]
Closed - The problem was that I haven't passed a proper `config` to the `ActorSystem` so it took "us-west" without any credentials by default. Though in truth the Exception could be more meaningful 😉
