### ISSUE TITLE
ElasticsearchTest

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#479]
```
----------------------------------------
Cluster Name: elasticsearch-cluster-runner
Base Path:    /tmp/es-cluster431932489297553471
----------------------------------------
Cluster Name: elasticsearch-cluster-runner
Base Path:    /tmp/es-cluster4836132851537540940
Num Of Node:  1
----------------------------------------
Num Of Node:  1
----------------------------------------
Creating /tmp/es-cluster431932489297553471/config/node_1
Creating /tmp/es-cluster4836132851537540940/config/node_1
Creating /tmp/es-cluster431932489297553471/logs/node_1
Creating /tmp/es-cluster431932489297553471/data/node_1
Creating /tmp/es-cluster4836132851537540940/logs/node_1
Creating /tmp/es-cluster4836132851537540940/data/node_1
Node Name:      Node 1
HTTP Port:      9211
Transport Port: 9311
Data Directory: /tmp/es-cluster4836132851537540940/data/node_1
Log Directory:  /tmp/es-cluster4836132851537540940/logs/node_1
----------------------------------------
Node Name:      Node 1
HTTP Port:      9201
Transport Port: 9301
Data Directory: /tmp/es-cluster431932489297553471/data/node_1
Log Directory:  /tmp/es-cluster431932489297553471/logs/node_1
----------------------------------------
Creating /tmp/es-cluster431932489297553471/modules
Creating /tmp/es-cluster431932489297553471/plugins
Creating /tmp/es-cluster4836132851537540940/modules
Creating /tmp/es-cluster4836132851537540940/plugins
[2017-09-19T11:38:00,030][INFO ][o.e.n.Node               ] [Node 1] initializing ...
[2017-09-19T11:38:00,029][INFO ][o.e.n.Node               ] [Node 1] initializing ...
[2017-09-19T11:38:00,174][INFO ][o.e.e.NodeEnvironment    ] [Node 1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [16gb], net total_space [29.4gb], spins? [no], types [ext4]
[2017-09-19T11:38:00,179][INFO ][o.e.e.NodeEnvironment    ] [Node 1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [16gb], net total_space [29.4gb], spins? [no], types [ext4]
[2017-09-19T11:38:00,189][INFO ][o.e.e.NodeEnvironment    ] [Node 1] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-09-19T11:38:00,192][INFO ][o.e.n.Node               ] [Node 1] node name [Node 1], node ID [0uo6S3NHSzihlcDfJqJ_-g]
[2017-09-19T11:38:00,194][INFO ][o.e.n.Node               ] [Node 1] version[5.6.0], pid[7311], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.4.0-93-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-09-19T11:38:00,198][INFO ][o.e.n.Node               ] [Node 1] JVM arguments [-Dfile.encoding=UTF8, -Xms1g, -Xmx1g, -Xss6M, -XX:+CMSClassUnloadingEnabled, -XX:+UseConcMarkSweepGC, -XX:ReservedCodeCacheSize=128m]
[2017-09-19T11:38:00,203][INFO ][o.e.e.NodeEnvironment    ] [Node 1] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] node name [Node 1], node ID [8SwMlrshQgqYibIM7hsSVw]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] version[5.6.0], pid[7311], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.4.0-93-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] JVM arguments [-Dfile.encoding=UTF8, -Xms1g, -Xmx1g, -Xss6M, -XX:+CMSClassUnloadingEnabled, -XX:+UseConcMarkSweepGC, -XX:ReservedCodeCacheSize=128m]
[2017-09-19T11:38:00,231][INFO ][o.e.p.PluginsService     ] [Node 1] no modules loaded
[2017-09-19T11:38:00,232][INFO ][o.e.p.PluginsService     ] [Node 1] no modules loaded
[2017-09-19T11:38:00,235][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2017-09-19T11:38:00,237][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.ingest.common.IngestCommonPlugin]
[2017-09-19T11:38:00,239][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.painless.PainlessPlugin]
[2017-09-19T11:38:00,241][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[2017-09-19T11:38:00,244][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.expression.ExpressionPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.groovy.GroovyPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2017-09-19T11:38:00,248][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2017-09-19T11:38:00,248][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.ingest.common.IngestCommonPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.painless.PainlessPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.expression.ExpressionPlugin]
[2017-09-19T11:38:00,254][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.groovy.GroovyPlugin]
[2017-09-19T11:38:00,255][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[2017-09-19T11:38:00,255][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin]
[2017-09-19T11:38:00,257][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[2017-09-19T11:38:00,257][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Closed all nodes.
Deleted /tmp/es-cluster4836132851537540940
[info] Test run started
[error] Test akka.stream.alpakka.elasticsearch.ElasticsearchTest failed: org.codelibs.elasticsearch.runner.ClusterRunnerException: Failed to start node 1, took 0.0 sec
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:360)
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:284)
[error]     at akka.stream.alpakka.elasticsearch.ElasticsearchTest.setup(ElasticsearchTest.java:43)
[error]     ...
[error] Caused by: java.lang.IllegalStateException: availableProcessors is already set to [2], rejecting [2]
[error]     at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
[error]     at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
[error]     at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:82)
[error]     at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:138)
[error]     at org.elasticsearch.transport.Netty4Plugin.lambda$getTransports$0(Netty4Plugin.java:93)
[error]     at org.elasticsearch.node.Node.<init>(Node.java:430)
[error]     at org.codelibs.elasticsearch.runner.node.ClusterRunnerNode.<init>(ClusterRunnerNode.java:17)
[error]     at org.codelibs.elasticsearch.runner.node.ClusterRunnerNode.<init>(ClusterRunnerNode.java:23)
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:355)
[error]     ... 50 more
[error] Test akka.stream.alpakka.elasticsearch.ElasticsearchTest failed: java.lang.NullPointerException: null, took 0.0 sec
[error]     at akka.stream.alpakka.elasticsearch.ElasticsearchTest.teardown(ElasticsearchTest.java:70)
[error]     ...
```

**Comment by takezoe** [comment]
Hmm... Maybe it's a timing issue. Since the author of elasticsearch-cluster-runner which is used for test is my collegue, we will investigate immediately.

**Comment by raboof** [comment]
Great! Indeed it could be a timing issue, as it doesn't fail all of the time.
