### ISSUE TITLE
json4s error during bintray release

### ISSUE THREAD

**Issue by raboof** [akka/alpakka#531]
While releasing, we see the following error in the logs:
```
java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
	at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:29)
	at org.json4s.native.JsonMethods$.render(JsonMethods.scala:62)
	at bintry.Methods$json$.str(Methods.scala:19)
	at bintry.Methods$Repo$Package$Version$Attrs$.update(Methods.scala:147)
	at bintray.BintrayRepo$$anonfun$publishVersionAttributes$1.apply(BintrayRepo.scala:23)
	at bintray.BintrayRepo$$anonfun$publishVersionAttributes$1.apply(BintrayRepo.scala:23)
	at bintray.Bintray$await$.ready(Bintray.scala:120)
	at bintray.BintrayRepo.publishVersionAttributes(BintrayRepo.scala:22)
	at bintray.BintrayPlugin$$anonfun$publishVersionAttributesTask$1.apply(BintrayPlugin.scala:147)
	at bintray.BintrayPlugin$$anonfun$publishVersionAttributesTask$1.apply(BintrayPlugin.scala:145)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The files in bintray appear to be fine however...

**Comment by raboof** [comment]
Indeed fixed by 1dc2714
