### ISSUE TITLE
elasticsearch connector fails to extract error from response

### ISSUE THREAD

**Issue by mbknor** [akka/alpakka#558]
When I get some error from elastic, the elasticsearch connector fails to extract the error-message and instead crashes:

```
Caused by: java.util.NoSuchElementException: key not found: result
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at akka.stream.alpakka.elasticsearch.ElasticsearchFlowStage$$anon$1.$anonfun$handleResponse$1(ElasticsearchFlowStage.scala:89)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
```

Example error:
```json
{
  "took": 18,
  "errors": true,
  "items": [
    {
      "index": {
        "_type": "asset",
        "_id": "1006725",
        "_index": "my-index-name",
        "error": {
          "type": "illegal_argument_exception",
          "reason": "Limit of total fields [1000] in index [my-index-name] has been exceeded"
        },
        "status": 400
      }
    },
    {
      "index": {
        "_type": "asset",
        "_version": 5,
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_id": "1006726",
        "_index": "my-index-name",
        "result": "updated",
        "status": 200,
        "created": false
      }
    }
  ]
}
```

**Comment by raboof** [comment]
@takezoe could you have a look?

**Comment by takezoe** [comment]
@raboof Yes, https://github.com/akka/alpakka/pull/504 fixes and improves error handling in `ElasticsearchFlowStage`. By that pull request, it becomes to retry failed documents specified times by `retryCount`. Finally, if the retried count is over `retryCount`, failed documents are sent to downstream as same as current implementation (but it has a bug as reported currently).

@mbknor Could you try #504?

**Comment by johanandren** [comment]
Seems I just missed closing this.
