### ISSUE TITLE
Failed: LogRotatorSink

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#559]
```
[info] - must write lines to multiple files due to filesize *** FAILED *** (50 milliseconds)
[info]   List(2002, 1001, 2002) did not contain the same elements as List(2002, 2002, 2002) (LogRotatorSinkSpec.scala:168)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.words.ResultOfContainWord.theSameElementsAs(ResultOfContainWord.scala:184)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(LogRotatorSinkSpec.scala:168)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(LogRotatorSinkSpec.scala:160)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.withFixture(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.runTest(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.runTests(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.org$scalatest$WordSpecLike$$super$run(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.org$scalatest$BeforeAndAfterAll$$super$run(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec.run(LogRotatorSinkSpec.scala:86)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:102)
[info]   at sbt.TestRunner.run(TestFramework.scala:113)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:258)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:229)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFunction.apply(TestFramework.scala:267)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:276)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:266)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by raboof** [comment]
@tg44 could you have a look at this one?

**Comment by tg44** [comment]
Ofc. It's seems like a "sometimes" error. I will check this later today.

**Comment by tg44** [comment]
Can sb link a failed build or reprod this issue? As I see this go throught in the recent builds without error like: https://travis-ci.org/akka/alpakka/builds/297324429

**Comment by raboof** [comment]
Indeed it doesn't consistently fail.... https://travis-ci.org/akka/alpakka/jobs/297956162 is a recent example.

**Comment by tg44** [comment]
I "love" these. Non reproductable mostly timing errors. :(

```
val testUntilFailed = Command.command("testUntilFailed") { state =>
  "testOnly akka.stream.alpakka.file.scaladsl.LogRotatorSinkSpec" :: "testUntilFailed" :: state
}
```
More than 50 run, 0 error... 

I hacked a better inner state which waits for all inner future. I make a new PR in minutes. Feel free to criticize it! (This future callback on the same thread, get an execution context from nowhere thing is a bit of blackmagic for me. There could be possible errors on my logic.)

**Comment by aserrallerios** [comment]
Failed build because `LogRotatorSink`

https://travis-ci.org/akka/alpakka/jobs/296274917

**Comment by raboof** [comment]
Let's close this and reopen when the problem persists after merging #568
