### ISSUE TITLE
Failed: JmsConnectorsSpec

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#560]
```
[info] - should publish and consume JMS text messages through a queue with client ack *** FAILED *** (5 seconds, 164 milliseconds)
[info]   Vector(ActiveMQTextMessage {commandId = 14, responseRequired = true, messageId = ID:travis-job-bab50f24-8371-420b-82da-a2c5d34bdbcd-33430-1509631829776-40:1:1:1:10, originalDestination = null, originalTransactionId = null, producerId = ID:travis-job-bab50f24-8371-420b-82da-a2c5d34bdbcd-33430-1509631829776-40:1:1:1, destination = queue://numbers, transactionId = null, expiration = 0, timestamp = 1509631836256, arrival = 0, brokerInTime = 1509631836256, brokerOutTime = 1509631836312, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = org.apache.activemq.util.ByteSequence@13881984, marshalledProperties = null, dataStructure = null, redeliveryCounter = 1, size = 0, properties = null, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false, text = 10}) was not empty 
JmsConnectorsSpec.scala:231)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7059)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec.$anonfun$new$23(JmsConnectorsSpec.scala:231)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec.$anonfun$new$23$adapted(JmsConnectorsSpec.scala:191)
[info]   at akka.stream.alpakka.jms.JmsSpec.withServer(JmsSpec.scala:44)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec.$anonfun$new$22(JmsConnectorsSpec.scala:191)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[info]   at akka.stream.alpakka.jms.JmsSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(JmsSpec.scala:15)
[info]   at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
[info]   at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
[info]   at akka.stream.alpakka.jms.JmsSpec.runTest(JmsSpec.scala:15)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
[info]   at akka.stream.alpakka.jms.JmsSpec.org$scalatest$BeforeAndAfterAll$$super$run(JmsSpec.scala:15)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.stream.alpakka.jms.JmsSpec.run(JmsSpec.scala:15)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:102)
[info]   at sbt.TestRunner.run(TestFramework.scala:113)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:258)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:229)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFunction.apply(TestFramework.scala:267)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:302)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:308)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:266)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by ennru** [comment]
A lot of builds went trough since reporting this.
