### ISSUE TITLE
Failed: KinesisFlow

### ISSUE THREAD

**Issue by aserrallerios** [akka/alpakka#561]
```
[info] - must publish records with retries *** FAILED *** (206 milliseconds)
[info]   java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 150 milliseconds
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:291)
[info]   at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:690)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$5.<init>(KinesisFlowSpec.scala:79)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(KinesisFlowSpec.scala:44)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(KinesisFlowSpec.scala:44)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.withFixture(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:221)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.runTest(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.runTests(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.org$scalatest$WordSpecLike$$super$run(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.org$scalatest$BeforeAndAfterAll$$super$run(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.stream.alpakka.kinesis.KinesisFlowSpec.run(KinesisFlowSpec.scala:24)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:102)
[info]   at sbt.TestRunner.run(TestFramework.scala:113)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:258)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:229)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:258)
[info]   at sbt.TestFunction.apply(TestFramework.scala:267)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:302)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:308)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:64)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:266)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

**Comment by aserrallerios** [comment]
I've seen this error only once. Maybe timeout is too low for this test.

I'll have a look.

**Comment by aserrallerios** [comment]
https://github.com/akka/alpakka/pull/565

**Comment by aserrallerios** [comment]
Will reopen if the failure reproduces again.
