### ISSUE TITLE
elasticsearch-connector only logs DEBUG-messages when not able to connect to elastic 

### ISSUE THREAD

**Issue by mbknor** [akka/alpakka#572]
Version 0.14

When streaming to elastic using elasticsearch-connector, and elastic is unreachable, ElasticsearchFlowStage ~~is not logging anything and is retrying forever.
except from not logging anything~~ is only logging DEBUG-messages. The retrying mechanism is working fine.

```
15:01:18.529 [pool-7-thread-1] DEBUG org.elasticsearch.client.RestClient - request [POST http://localhost:9200/_bulk] failed
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)```

**Comment by ennru** [comment]
@mbknor Do you have a suggestion how to fix this?
