### ISSUE TITLE
Exception with Slick JDBC connector for MS SQL Server

### ISSUE THREAD

**Issue by indusbull** [akka/alpakka#579]
I am trying[ Slick (JDBC) Connector tutorial](https://developer.lightbend.com/docs/alpakka/current/slick.html) to connect to MS SQL Server 2012 in my prototype Java Akka project. But I am having difficulties since last few hours to connect to DB through JDBC. It keeps throwing below exception - Not sure what I am missing either in config or code. It is simple example.

**Exception:**
`java.sql.SQLTransientConnectionException: slick-sqlserver.db - Connection is not available, request timed out after 1001ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:438)
at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:216)
at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:215)
at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:279)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`

**application.config**
` slick-sqlserver {
       profile = "slick.jdbc.SQLServerProfile$"
       db {
          dataSourceClass = "slick.jdbc.DriverDataSource"
          properties = {
              driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver3;databaseName=dbname"
              url = "jdbc:sqlserver://host:1433"
              user = "username"
              password = "password"
         }
    }
 }`

**My Code**

` ActorSystem system = ActorSystem.create("testSystem");
 final Materializer materializer = ActorMaterializer.create(system);

    final SlickSession session = SlickSession.forConfig("slick-sqlserver");

    final CompletionStage<Done> done =
      Slick
        .source(
          session,
          "SELECT 1",
          //(SlickRow row) -> new Object(row.nextInt(), row.nextString())
          (SlickRow row) -> new Object()
        )
        .log("user")
        .runWith(Sink.ignore(), materializer);

    done.whenComplete((value, exception) -> {
      session.close();
      system.terminate();
    });`

**Comment by raboof** [comment]
We try to use github issues only for bugs and features, not for questions and troubleshooting. You might have more luck at gitter (https://gitter.im/akka/akka or https://gitter.im/slick/slick), our mailinglists (https://groups.google.com/forum/#!forum/akka-user or http://groups.google.com/group/scalaquery) or on stackoverflow.

One first thing to try: is your firewall allowing connections to `host:1433`? (you can check with for example telnet)

**Comment by indusbull** [comment]
@raboof  yes firewall is open. Thanks

I will ask the question on other forums as you mentioned.

**Comment by raboof** [comment]
Thanks!
