### ISSUE TITLE
S3 '@' in the file name generates a bad signature

### ISSUE THREAD

**Issue by dispalt** [akka/alpakka#719]
It appears when you have a path that includes an @ symbol it improperly calculates the signature and generates an error.

**Comment by josephpford** [comment]
Can you share the error?  

I'm getting the following error and I don't know what the AWS s3 key is that is generating the error, but I'm 99% positive it's while it is doing a listBucket to fetch all the keys from a bucket with prefix.

org.xml.sax.SAXParseException: Character reference "&#
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1437) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanCharReferenceValue(XMLScanner.java:1321) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3059) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649) ~[na:1.8.0_60]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333) ~[na:1.8.0_60]
	at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:41) ~[scala-xml_2.11-1.0.6.jar:na]
	at scala.xml.XML$$anon$1.loadXML(XML.scala:71) ~[scala-xml_2.11-1.0.6.jar:na]
	at scala.xml.factory.XMLLoader$class.load(XMLLoader.scala:54) ~[scala-xml_2.11-1.0.6.jar:na]
	at scala.xml.XML$$anon$1.load(XML.scala:71) ~[scala-xml_2.11-1.0.6.jar:na]
	at akka.http.scaladsl.marshallers.xml.ScalaXmlSupport$$anonfun$nodeSeqUnmarshaller$1.apply(ScalaXmlSupport.scala:30) ~[akka-http-xml_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.marshallers.xml.ScalaXmlSupport$$anonfun$nodeSeqUnmarshaller$1.apply(ScalaXmlSupport.scala:27) ~[akka-http-xml_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$mapWithCharset$extension$1.apply(Unmarshaller.scala:99) ~[akka-http_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$mapWithCharset$extension$1.apply(Unmarshaller.scala:99) ~[akka-http_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedUnmarshaller$$anonfun$mapWithInput$extension$1$$anonfun$apply$18$$anonfun$apply$19$$anonfun$apply$20.apply(Unmarshaller.scala:91) ~[akka-http_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.util.FastFuture$$anonfun$map$extension$1.apply(FastFuture.scala:23) ~[akka-http-core_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.util.FastFuture$$anonfun$map$extension$1.apply(FastFuture.scala:23) ~[akka-http-core_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.util.FastFuture$.akka$http$scaladsl$util$FastFuture$$strictTransform$1(FastFuture.scala:41) ~[akka-http-core_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:51) ~[akka-http-core_2.11-10.0.9.jar:na]
	at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:50) ~[akka-http-core_2.11-10.0.9.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:36) ~[scala-library-2.11.11.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala) ~[scala-library-2.11.11.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.5.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.11.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[akka-actor_2.11-2.5.4.jar:na]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[akka-actor_2.11-2.5.4.jar:na]
