### ISSUE TITLE
MqttFlowStage does not tolerate already having been disconnected

### ISSUE THREAD

**Issue by huntc** [akka/alpakka#805]
It appears as though the `postStop` method of `MqttFlowStage` doesn't tolerate already being disconnected, which then causes an error:

```
[ERROR] [02/22/2018 15:18:33.374] [lora-server-akka.actor.default-dispatcher-5] [akka://lora-server/user/StreamSupervisor-0/flow-13-0-ignoreSink] Error during postStop in [akka.stream.alpakka.mqtt.MqttFlowStage@2cae551d]: Client is disconnected
Client is disconnected (32101)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:489)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:826)
	at akka.stream.alpakka.mqtt.MqttFlowStage$$anon$2.postStop(MqttFlowStage.scala:244)
```

This is a particular problem because it occurs when an MQTT client loses connectivity with its broker - this happens often in my case.

I suggest that the following line in `postStop` is surrounded by a try/catch for `MqttException`:

```
mqttClient.disconnect(
```

**Comment by 2m** [comment]
Thanks for making the connector more robust! :)
