### ISSUE TITLE
s3 upload fails on empty source

### ISSUE THREAD

**Issue by eyalfa** [akka/alpakka#806]
when trying to upload an empty file, we're getting this exception:
```
The future returned an exception of type: java.lang.RuntimeException, with message: No Responses.
ScalaTestFailureLocation: akka.stream.alpakka.s3.scaladsl.S3SinkSpec at (S3SinkSpec.scala:79)
org.scalatest.exceptions.TestFailedException: The future returned an exception of type: java.lang.RuntimeException, with message: No Responses.
	at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.$anonfun$new$4(S3SinkSpec.scala:79)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.withFixture(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.runTest(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.runTests(S3SinkSpec.scala:16)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.org$scalatest$FlatSpecLike$$super$run(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.org$scalatest$BeforeAndAfterAll$$super$run(S3SinkSpec.scala:16)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.run(S3SinkSpec.scala:16)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: java.lang.RuntimeException: No Responses
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$completionSink$2(S3Stream.scala:327)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I was able to reproduce in a simple test case [here](https://github.com/eyalfa/alpakka/blob/empty-s3-upload-fails/s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala#L67-L80),
as far as I understand s3 supports empty files/objects and this seems to be a library bug, as the library simply fails to produce any request for such cases.

I'm willing to take a stub at this and submit a pull request if the community agrees this is indeed a bug.

cc @jypma (as you seem to be the original author)

**Comment by ennru** [comment]
Yes, please. Please have a go on fixing this.

**Comment by jypma** [comment]
Indeed. This totally is a bug, thanks a lot for spotting it.

**Comment by eyalfa** [comment]
@ennru ,
I'm trying to fix this by conditionally appending an empty ByteString to the input stream,
but for some reason the test fails with 'Cannot find etag', I've made the error message a bit more verbose and now I'm seeing this:

> akka.stream.alpakka.s3.impl.FailedUpload, with message: Cannot find etag in List(Cache-Control: must-revalidate, no-cache, no-store, Server: Jetty (9.2.13.v20150730)).

furthermore, when debugging this, the test succeeds.

BTW, the happens for the empty input test case.

**Comment by jypma** [comment]
Maybe S3 doesn't set an `ETag` on the response if the body was empty? That'd be weird though...

**Comment by eyalfa** [comment]
this was indeed a problem with mockUpload:

put(urlEqualTo(s"/$bucketKey?partNumber=1&uploadId=$uploadId"))
        .withRequestBody(matching(**body**))
        .willReturn(

this mock was written under the assumption all tests will upload the expected body, mine uploads an empty one.
