### ISSUE TITLE
RestartSource/Sink not working with AmqpCachedConnectionProvider

### ISSUE THREAD

**Issue by pliljenberg** [akka/alpakka#842]
After changing to use the `AmqpCachedConnectionProvider` (in order to minimize number of open connections) the `RestartSource` stops working. The Source will be finished with an error when RabbitMQ shuts down.
The code below works, it will recover when RabbitMQ has been restarted. Removing the comments and enabling the `AmqpCachedConnectionProvider` it will just stop the Flow with the error message:

    [ERROR] [03/17/2018 14:46:14.561] [MySpec-akka.actor.default-dispatcher-3] [akka://MySpec/user/StreamSupervisor-0/flow-0-0-ignoreSink] Error during postStop in [akka.stream.alpakka.amqp.AmqpSourceStage@4333f384]: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
    com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:875)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:991)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:920)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:904)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:896)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.close(AutorecoveringConnection.java:216)
	at akka.stream.alpakka.amqp.AmqpConnectionProvider.release(AmqpConnectionProvider.scala:21)
	at akka.stream.alpakka.amqp.AmqpConnectionProvider.release$(AmqpConnectionProvider.scala:21)
	at akka.stream.alpakka.amqp.AmqpDetailsConnectionProvider.release(AmqpConnectionProvider.scala:52)
	at akka.stream.alpakka.amqp.AmqpCachedConnectionProvider.release(AmqpConnectionProvider.scala:241)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.postStop(AmqpConnector.scala:80)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.postStop$(AmqpConnector.scala:77)
	at akka.stream.alpakka.amqp.AmqpSourceStage$$anon$1.postStop(AmqpSourceStage.scala:49)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:564)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:545)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:460)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:465)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

    [ERROR] [03/17/2018 14:46:14.563] [MySpec-akka.actor.default-dispatcher-3] [RestartWithBackoffSource(akka://MySpec)] Restarting graph due to failure
    com.rabbitmq.client.ShutdownSignalException: connection error; protocol method: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)
	at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:870)
	at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:860)
	at com.rabbitmq.client.impl.AMQConnection.handleConnectionClose(AMQConnection.java:798)
	at com.rabbitmq.client.impl.AMQConnection.processControlCommand(AMQConnection.java:753)
	at com.rabbitmq.client.impl.AMQConnection$1.processAsync(AMQConnection.java:237)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:623)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:47)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:581)
	at java.base/java.lang.Thread.run(Thread.java:844)

Code:

    import scala.concurrent.duration._
    implicit val mat = ActorMaterializer()

    val (min, max, random) = (1.seconds, 10.seconds, 0.2)

    val connectionProvider =
    //  AmqpCachedConnectionProvider(
      AmqpDetailsConnectionProvider(
        "localhost", 5672
      )
        .withVirtualHost("/")
        .withCredentials(AmqpCredentials("user", "password"))
        .withAutomaticRecoveryEnabled(true)
        .withTopologyRecoveryEnabled(true)
        .withNetworkRecoveryInterval(10)
        .withRequestedHeartbeat(10)
    //    )
    val exchangeDeclaration = ExchangeDeclaration(
      "exchange",
      "topic",
      durable = true
    )

    val source = AmqpSource.committableSource(
      TemporaryQueueSourceSettings(connectionProvider, exchangeDeclaration.name, routingKey = Some("test"))
        .withDeclarations(exchangeDeclaration),
      bufferSize = 1
    )

    RestartSource
      .withBackoff(min, max, random) { () => source }
      .runWith(Sink.ignore)

   
Is this to be expected?

**Comment by ennru** [comment]
@juanjoDiaz Any input on this?

**Comment by juanjoDiaz** [comment]
It's a bug. Thanks for reporting!
I just PR'd the fix

**Comment by pliljenberg** [comment]
Nice! Verified that the latest version on master works :)
However; if Rabbit is not available when I start it still fails (with another error) and will not retry to connect. Should I open another ticket for this or is that the contract?

**Comment by juanjoDiaz** [comment]
@pliljenberg can you post here the error that you get? I'll take a look  at it :)

**Comment by pliljenberg** [comment]
[ERROR] [03/19/2018 11:11:53.449] [MySpec-akka.actor.default-dispatcher-4] [akka://MySpec/user/StreamSupervisor-0/flow-0-0-ignoreSink] Error during preStart in [akka.stream.alpakka.amqp.AmqpSourceStage@56d05180]: null
    java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:362)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:948)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:907)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:784)
	at akka.stream.alpakka.amqp.AmqpDetailsConnectionProvider.get(AmqpConnectionProvider.scala:129)
	at akka.stream.alpakka.amqp.AmqpCachedConnectionProvider.get(AmqpConnectionProvider.scala:217)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.preStart(AmqpConnector.scala:26)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.preStart$(AmqpConnector.scala:24)
	at akka.stream.alpakka.amqp.AmqpSourceStage$$anon$1.preStart(AmqpSourceStage.scala:49)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:293)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:554)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:676)
	at akka.stream.impl.fusing.ActorGraphInterpreter.finishShellRegistration(ActorGraphInterpreter.scala:718)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:733)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:726)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:667)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:306)
	... 29 more
    Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by juanjoDiaz** [comment]
I copy-pasted your code and couldn't reproduce the error.
Maybe you can open a new ticket explaining a bit more.
