### ISSUE TITLE
JMS test failures: should publish and consume JMS text messages through a queue with client ack

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#845]
Recently the build fails for a lot of differnt tests most probably connected to the memory limit of 4G on Travis.

This failure shows quite often:
```
[info] The JMS Connectors
[info] - should publish and consume JMS text messages through a queue with client ack *** FAILED *** (5 seconds, 174 milliseconds)
[info]   Vector(ActiveMQTextMessage {commandId = 14, responseRequired = true, messageId = ID:travis-job-a8334e00-d7c2-4efb-8a04-e2114cb80f44-39146-1521451463381-202:1:1:1:10, originalDestination = null, originalTransactionId = null, producerId = ID:travis-job-a8334e00-d7c2-4efb-8a04-e2114cb80f44-39146-1521451463381-202:1:1:1, destination = queue://numbers, transactionId = null, expiration = 0, timestamp = 1521451569462, arrival = 0, brokerInTime = 1521451569462, brokerOutTime = 1521451569512, correlationId = null, replyTo = null, persistent = true, type = null, priority = 4, groupID = null, groupSequence = 0, targetConsumerId = null, compressed = false, userID = null, content = org.apache.activemq.util.ByteSequence@110f088e, marshalledProperties = null, dataStructure = null, redeliveryCounter = 1, size = 0, properties = null, readOnlyProperties = true, readOnlyBody = true, droppable = false, jmsXGroupFirstForConsumer = false, text = 10}) was not empty (JmsConnectorsSpec.scala:391)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7059)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$30.apply(JmsConnectorsSpec.scala:391)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec$$anonfun$1$$anonfun$apply$mcV$sp$11$$anonfun$apply$mcV$sp$30.apply(JmsConnectorsSpec.scala:352)
[info]   at akka.stream.alpakka.jms.JmsSpec.withServer(JmsSpec.scala:48)
```

**Comment by russellyou** [comment]
Is this still the case ? I believe I have done something to this test case (already merged to master)

https://github.com/akka/alpakka/pull/867/files

**Comment by ennru** [comment]
We've a few tests that show up more often than others as failures on Travis. We'll work with the build to isolate modules.

**Comment by ennru** [comment]
This hasn't shown for a long time and Alpakka JMS has improved a lot.
Closing.
