### ISSUE TITLE
Failure to start stream when RabbitMQ is not started

### ISSUE THREAD

**Issue by pliljenberg** [akka/alpakka#854]
Opened from #842, sorry for the duplication of code/logs. 

Starting from scratch, meaning that no RabbitMQ server is running. When starting the code the connection (obviously) fails. What I expected was that the `Restarting` code would retry to connect in a similar way as when the connection is lost during processing.
Now the code just throws and exceptions and stops.
It works if I don't use the `AmqpCachedConnectionProvider`- then it tries to connect "forever".

Tested with a local build of alpakka: `0.17+26-033d820f` 

The error message is thrown.

**Code:**

    import scala.concurrent.duration._
    implicit val mat = ActorMaterializer()

    val (min, max, random) = (1.seconds, 10.seconds, 0.2)

    val connectionProvider =
    /** Adding this breaks
       AmqpCachedConnectionProvider( 
    **/
      AmqpDetailsConnectionProvider(
        "localhost", 5672
      )
        .withVirtualHost("/")
        .withCredentials(AmqpCredentials("user", "password"))
        .withAutomaticRecoveryEnabled(true)
        .withTopologyRecoveryEnabled(true)
        .withNetworkRecoveryInterval(10)
        .withRequestedHeartbeat(10)
    )
    // )
    val exchangeDeclaration = ExchangeDeclaration(
      "exchange",
      "topic",
      durable = true
    )

    val source = AmqpSource.committableSource(
      TemporaryQueueSourceSettings(connectionProvider, exchangeDeclaration.name, routingKey = Some("test"))
        .withDeclarations(exchangeDeclaration),
      bufferSize = 1
    )

    RestartSource
      .withBackoff(min, max, random) { () => source }
      .runWith(Sink.ignore)

   
**Error:**
 
    [ERROR] [03/19/2018 11:11:53.449] [MySpec-akka.actor.default-dispatcher-4] [akka://MySpec/user/StreamSupervisor-0/flow-0-0-ignoreSink] Error during preStart in [akka.stream.alpakka.amqp.AmqpSourceStage@56d05180]: null
    java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:362)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:99)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:948)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:907)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:784)
	at akka.stream.alpakka.amqp.AmqpDetailsConnectionProvider.get(AmqpConnectionProvider.scala:129)
	at akka.stream.alpakka.amqp.AmqpCachedConnectionProvider.get(AmqpConnectionProvider.scala:217)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.preStart(AmqpConnector.scala:26)
	at akka.stream.alpakka.amqp.AmqpConnectorLogic.preStart$(AmqpConnector.scala:24)
	at akka.stream.alpakka.amqp.AmqpSourceStage$$anon$1.preStart(AmqpSourceStage.scala:49)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:293)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:554)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:676)
	at akka.stream.impl.fusing.ActorGraphInterpreter.finishShellRegistration(ActorGraphInterpreter.scala:718)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:733)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:726)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:667)
	at akka.actor.ActorCell.create(ActorCell.scala:591)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:66)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:306)
	... 29 more
    Caused by: java.io.EOFException
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295)
	at com.rabbitmq.client.impl.Frame.readFrom(Frame.java:91)
	at com.rabbitmq.client.impl.SocketFrameHandler.readFrame(SocketFrameHandler.java:164)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:580)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by pliljenberg** [comment]
Looks like this was fixed by #848 - great! Looking forward to next release 👍
