### ISSUE TITLE
JmsConnectorsSpec fails for unexpected resend when acked

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#857]
It looks like as if the acknowledge sometimes happens too late on Travis so that the last message gets resent.

```
[info] - should publish and consume JMS text messages through a queue with client ack *** FAILED *** (5 seconds, 172 milliseconds)
[info]   Vector(ActiveMQTextMessage {commandId = 14, .... , text = 10}) was not empty (JmsConnectorsSpec.scala:391)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7059)
[info]   at akka.stream.alpakka.jms.scaladsl.JmsConnectorsSpec.$anonfun$new$34(JmsConnectorsSpec.scala:391)
```

**Comment by ennru** [comment]
This hasn't shown for a long while now.
Closing.
