### ISSUE TITLE
S3 DiskBuffer test fails sporadically

### ISSUE THREAD

**Issue by agolubev** [akka/alpakka#87]
```
[info] DiskBuffer
[info] - should emit a chunk on its output containing the concatenation of all input values *** FAILED *** (827 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 6 times, sleeping 15 milliseconds between each query. (DiskBufferSpec.scala:39)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.stream.alpakka.s3.impl.DiskBufferSpec$$anonfun$1.apply(DiskBufferSpec.scala:39)
[info]   at akka.stream.alpakka.s3.impl.DiskBufferSpec$$anonfun$1.apply(DiskBufferSpec.scala:30)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.stream.alpakka.s3.impl.DiskBufferSpec.withFixture(DiskBufferSpec.scala:17)
```

**Comment by johanandren** [comment]
90ms before failing seems extremely tight for running on a CI server, needs PatienceConfig with much higher value (in the Akka build we usually do somewhere along 3-5 seconds)

**Comment by agolubev** [comment]
Ok, will add this

**Comment by ennru** [comment]
Nothing we've seen for a long time, I reckon the patience in #113 solved this.
