### ISSUE TITLE
Slick fails in build

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#927]
Started to see this failure on Friday.
```
+slick/testChanged
saving stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/Appender
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:124)
	at sbt.StandardMain$.initialState(Main.scala:149)
	at sbt.xMain.run(Main.scala:75)
```

**Comment by 2m** [comment]
Was a problem with a Travis cache:
```
adding /home/travis/.ivy2/cache to cache
creating directory /home/travis/.ivy2/cache
adding /home/travis/.sbt/boot to cache
creating directory /home/travis/.sbt/boot
/home/travis/.sbt/boot/scala-2.12.4/org.scala-sbt/sbt/1.1.4/log4j-core-2.8.1.jar: Permission denied
```

Fixed it by purging all caches for master:
```
➜  alpakka git:(master) travis cache --delete --branch master
DANGER ZONE: Do you really want to delete all caches on branch master? |no| yes
```

If some PR validation fails with the same `NoClassDefFoundError` error, that PR needs to have its cache purged as well, as caches are indexed by branch.
