### ISSUE TITLE
MQTT: MqttSourceTest.supportWillMessage failed

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#928]
```
[error] Test akka.stream.alpakka.mqtt.javadsl.MqttSourceTest.supportWillMessage failed: java.util.concurrent.ExecutionException: Connection lost (32109) - java.net.SocketException: Connection reset, took 0.338 sec
[error]     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.scala$concurrent$java8$FuturesConvertersImpl$CF$$super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF$$anonfun$get$2.apply(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.package$.blocking(package.scala:123)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at akka.stream.alpakka.mqtt.javadsl.MqttSourceTest.supportWillMessage(MqttSourceTest.java:264)
[error]     ...
[error] Caused by: Connection lost (32109) - java.net.SocketException: Connection reset
[error]     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
[error]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[error]     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[error]     ... 3 more
[error] Caused by: java.net.SocketException: Connection reset
[error]     at java.net.SocketInputStream.read(SocketInputStream.java:210)
[error]     at java.net.SocketInputStream.read(SocketInputStream.java:141)
[error]     at java.net.SocketInputStream.read(SocketInputStream.java:224)
[error]     at java.io.DataInputStream.readByte(DataInputStream.java:265)
[error]     at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
[error]     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
[error]     ... 7 more
```

**Comment by 2m** [comment]
Another one https://travis-ci.org/akka/alpakka/jobs/381542617

**Comment by ennru** [comment]
We haven't seen this failure for a while, closing.
