### ISSUE TITLE
MQTT: Flow should automatically reconnect failed

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#929]
```
[info] mqtt flow
[info] - should automatically reconnect *** FAILED *** (83 milliseconds)
[info]   java.lang.AssertionError: expected OnNext, found OnError(Connection lost (32109) - java.net.SocketException: Connection reset
[info] 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
[info] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[info] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] 	at java.lang.Thread.run(Thread.java:748)
[info] Caused by: java.net.SocketException: Connection reset
[info] 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
[info] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[info] 	at java.net.SocketInputStream.read(SocketInputStream.java:224)
[info] 	at java.io.DataInputStream.readByte(DataInputStream.java:265)
[info] 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
[info] 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
[info] 	... 7 more
[info] )
```

**Comment by ennru** [comment]
It seems to be the second run on Travis that fails now that #932 is merged. Something might be left in a bad state in the MQTT server.
The Restart seems to kick in on the second run:
```
[ERROR] [05/08/2018 08:56:37.484] [MqttSourceSpec-akka.actor.default-dispatcher-8] [RestartWithBackoffSource(akka://MqttSourceSpec)] Restarting graph due to failure
Unable to connect to server (32103) - java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:94)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:701)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
```

**Comment by 2m** [comment]
Second run here as well: https://travis-ci.org/akka/alpakka/jobs/381541973

**Comment by ennru** [comment]
We haven't seen this failure for a while, closing.
