### ISSUE TITLE
ES connector throwing NoSuchElementException on Elasticsearch 2.4.6

### ISSUE THREAD

**Issue by brunoballekens** [akka/alpakka#945]
I use the ElasicsearchSink to insert documents in an index in bulk.
It works perfectly on elastic search version `5.6.8`, but on `2.4.6` it fails with the following exception:
```
java.util.NoSuchElementException: key not found: index
	at scala.collection.immutable.Map$Map1.apply(Map.scala:111)
	at akka.stream.alpakka.elasticsearch.ElasticsearchFlowStage$$anon$1.$anonfun$handleResponse$1(ElasticsearchFlowStage.scala:153)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at akka.stream.alpakka.elasticsearch.ElasticsearchFlowStage$$anon$1.handleResponse(ElasticsearchFlowStage.scala:151)
	at akka.stream.alpakka.elasticsearch.ElasticsearchFlowStage$$anon$1.$anonfun$responseHandler$1(ElasticsearchFlowStage.scala:107)
	at akka.stream.alpakka.elasticsearch.ElasticsearchFlowStage$$anon$1.$anonfun$responseHandler$1$adapted(ElasticsearchFlowStage.scala:107)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:454)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
ES (2.4.6) gives the following response to the bulk request:
```json
{
  "took": 132,
  "errors": false,
  "items": [{
    "create": {
      "_type": "... edited ...",
      "_version": 1,
      "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
      },
      "_id": "AWNFkDk_4aiXcpyYm1iC",
      "_index": "... edited ...",
      "status": 201
    }
  }]
}
```
ES (5.6.8) gives the following response to the bulk request:
```json
{
  "took": 11,
  "errors": false,
  "items": [{
      "index": {
        "_type": "... edited ...",
        "_version": 1,
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_id": "AWNFl3b1Vb8oV3T2XsH9",
        "_index": "... edited ...",
        "result": "created",
        "status": 201,
        "created": true
      }
    }]
}
```

Is Elasticsearch 2.4 supported by the alpakka connector ?

**Comment by ennru** [comment]
Thank you for reporting your problem. 
The structure of the responses from ES changed quite a lot, as you documented nicely here. The Alpakka Elasticsearch connector is not version-aware -- it does not do different things depending on the server's version. We use the Elasticsearch REST client in version 5.5.3, but a lot of REST writing and reading is done in Alpakka.
So in short, it does not support the feature you wanted to use, but others might work. Sorry for not being more specific.

**Comment by takezoe** [comment]
In this case, it seems to work by above fix. However Elasticsearch's version up is quite rapid and often contains breaking changes. So I think it's not realistic to guarantee support for old versions of Elasticsearch over the future.

**Comment by brunoballekens** [comment]
Sure, but that's a reason more to document the Elastic search version(s) with which the alpakka connector has been tested with.

**Comment by ennru** [comment]
Yes, we plan to be more specific on which versions the Alpakka connectors are developed with.

**Comment by ennru** [comment]
With #2277 we Alpakka Elasticsearch can now be configured for ES v5 and v7/

**Comment by ennru** [comment]
While this doesn't solve compatibility with ES 2.4, it shows at least that it is not expected to work well with v2.4.
