### ISSUE TITLE
AWS S3: JAXB classes not found on JRE 10

### ISSUE THREAD

**Issue by azolotko** [akka/alpakka#952]
akka-stream-alpakka-s3 version: 0.19
Scala version: 2.12.6

```
java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment Zulu10.2+3 (build 10.0.1+9)
OpenJDK 64-Bit Server VM Zulu10.2+3 (build 10.0.1+9, mixed mode)
```

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at akka.stream.alpakka.s3.auth.package$.encodeHex(package.scala:16)
	at akka.stream.alpakka.s3.auth.Signer$.$anonfun$signedRequest$1(Signer.scala:24)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by azolotko** [comment]
A workaround:
```sbt
libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.0"
```

**Comment by ennru** [comment]
As far as I can see, we're only using the byte array to hex conversion from JAXB. 
Is that available somewhere else in the Java base module?
Seems reasonable to implement again otherwise, so we don't need an extra dependency.
