### ISSUE TITLE
OrientDBTest.flow failed

### ISSUE THREAD

**Issue by ennru** [akka/alpakka#963]
Failed after unrelated changes on 2018-05-21

```
[ERROR] [05/20/2018 05:03:49.370] [default-akka.actor.default-dispatcher-6] [akka://default/system/StreamSupervisor-1/flow-5-0-seqSink] Error during postStop in [akka.stream.alpakka.orientdb.OrientDBSourceStage@657e6235]: null
java.lang.NullPointerException
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$PoolPartition.access$700(OPartitionedDatabasePool.java:418)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.close(OPartitionedDatabasePool.java:479)
	at akka.stream.alpakka.orientdb.OrientDBSourceLogic.postStop(OrientDBSourceStage.scala:71)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:552)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:426)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:558)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.create(ActorCell.scala:652)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] Test akka.stream.alpakka.orientdb.OrientDBTest.flow failed: java.util.concurrent.ExecutionException: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot copy a closed db
[error] 	DB name="GratefulDeadConcertsJava", took 0.139 sec
[error]     at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.$anonfun$get$2(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.package$.blocking(package.scala:142)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at akka.stream.alpakka.orientdb.OrientDBTest.flow(OrientDBTest.java:391)
[error]     ...
[error] Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot copy a closed db
[error] 	DB name="GratefulDeadConcertsJava"
[error]     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.copy(ODatabaseDocumentTx.java:564)
[error]     at com.orientechnologies.orient.core.sql.query.OSQLNonBlockingQuery.execute(OSQLNonBlockingQuery.java:267)
[error]     at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:760)
[error]     at akka.stream.alpakka.orientdb.OrientDBSourceLogic.sendOSQLRequest(OrientDBSourceStage.scala:84)
[error]     at akka.stream.alpakka.orientdb.OrientDBSourceLogic.onPull(OrientDBSourceStage.scala:139)
[error]     at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)

```

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/475052689

**Comment by 2m** [comment]
https://travis-ci.org/akka/alpakka/jobs/480834662

**Comment by ennru** [comment]
This was before the make-over of OrientDB in #1445.
Closing.
