### ISSUE TITLE
Aplakka Google PubSub with Emulator: unsupported Content-Type exception

### ISSUE THREAD

**Issue by damianbl** [akka/alpakka#981]
I run `akka-stream-alpakka-google-cloud-pub-sub` version 0.19 with Google PubSub Emulator and get this exception:

> akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException: Unsupported Content-Type, supported: application/json
> 	at akka.http.scaladsl.unmarshalling.Unmarshaller$UnsupportedContentTypeException$.apply(Unmarshaller.scala:158)
> 	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:114)
> 	at akka.http.scaladsl.unmarshalling.Unmarshaller$EnhancedFromEntityUnmarshaller$$anonfun$forContentTypes$extension$1$$anonfun$apply$24$$anonfun$apply$25.apply(Unmarshaller.scala:111)
> 	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
> 	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anonfun$transform$1$$anonfun$apply$2$$anonfun$apply$3.apply(Unmarshaller.scala:23)

**Comment by damianbl** [comment]
The actual content type I get is `application/octet-stream`

**Comment by damianbl** [comment]
It fails in GooglePubSubSource:34:

`session.getToken()`

**Comment by damianbl** [comment]
It should be fixed with this PR:

https://github.com/akka/alpakka/pull/982
